feat(snackbar): Add  input for custom position strategy#10126 - master
IgniteUI/igniteui-angular pull request #10133
Opened 2021-09-15 11:39 UTC by dobromirts

Closes #10126 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-09-16 06:04 UTC, hanastasov requested changes
Passing OverlaySettings to the snackbar open method, treats the sobject as message to display,

2021-09-16 07:42 UTC, zdrawku reviewed
@dobromirts Update the default snackbar animation to match the fade in/out animation from the [material spec](https://material-ui.com/components/snackbars/).

![snackbar](https://user-images.githubusercontent.com/11193764/133571090-2587118b-ddf8-4b1e-b035-3d979ab614f8.gif)

2021-09-16 09:05 UTC, hanastasov requested changes
Let's fix same issues for the toast component and the toggle method.

2021-09-16 10:34 UTC, hanastasov submitted a review, later dismissed

2021-09-17 07:37 UTC, zdrawku approved these changes

2021-09-17 07:37 UTC, merged