fix(grid): use formattter function for boolean columns #8978
IgniteUI/igniteui-angular pull request #10154
Opened 2021-09-17 15:02 UTC by Volen99

Closes #8978

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-09-20 06:37 UTC, hanastasov requested changes
Even though these are only tests, try to set more suitable names to the column. For example. instead of `IsDev`, set a column name that others will easily understand and that makes sense in conjuction with the other column names: `ID` and `Name`. SO, for example:

`ID`, `Name`, `IsEmployed`, or `isStudent, etc`.

2021-09-21 07:13 UTC, ddincheva commented
While testing I have noticed some regression when no formatter is set to the boolean column the text and the icon is displayed 
![image](https://user-images.githubusercontent.com/34240583/134126729-7e76876b-9ad1-4c7a-873e-16c358bb1d85.png)
but in this case, only the icon should be displayed
![image](https://user-images.githubusercontent.com/34240583/134127090-9eb175f2-53cf-4700-9f37-116913ce8dc8.png)

Also please consider adding this fix for the expandable-cell.component and tree-cell.component as well.

2021-09-27 06:39 UTC, ddincheva commented
The issues have been fixed ... but I think you can improve the fix because currently when there is no formatter on the boolean columns unnecessary empty div is rendered in the dom 
![image](https://user-images.githubusercontent.com/34240583/134856833-4c145b82-00c4-4bb1-a559-2a76d23874b7.png)

2021-09-28 06:16 UTC, hanastasov approved these changes

2021-09-28 07:25 UTC, merged