Angular 13 - Bump nodejs and typescript
IgniteUI/igniteui-angular pull request #10403
Opened 2021-11-02 07:02 UTC by IvayloG

[Changes and deprecations in version 13](https://rc.angular.io/guide/update-to-latest-version#changes-and-deprecations-in-version-13)

- [x] NodeJS versions older than v12.20.0 are no longer supported. The Angular packages now use the NodeJS package exports feature with subpath patterns and requires a NodeJS version above 14.15.0 or 16.10.0.
- [x]  TypeScript versions older than 4.4.2 are no longer supported.

Note:
With the current setup the CI automatically picks higher minor version than the specified 14.**15**.0

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-11-03 08:37 UTC, Lipata requested changes

2021-11-03 08:37 UTC, Lipata commented on projects/igniteui-angular/schematics/ng-add/index.ts
>  import { chain, Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
Can you also remove the prompt setting for the ng-add schematic in the schema.json file?

2021-11-03 09:07 UTC, Lipata approved these changes

2021-11-04 08:16 UTC, kdinev commented
@IvayloG Since some of the work for removing IE11 is done in the branch @rkaraivanov works in, I'm retargeting your PR to that branch. Whenever you're ready with your work, just merge the PR.

2021-11-04 09:55 UTC, merged