Use columnList internally, keep public columns prop
IgniteUI/igniteui-angular pull request #10458
Opened 2021-11-09 13:27 UTC by hanastasov

Closes #7681

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-11-09 15:15 UTC, kdinev approved these changes

2021-11-10 07:23 UTC, rkaraivanov requested changes

2021-11-10 07:23 UTC, rkaraivanov commented on projects/igniteui-angular/src/lib/grids/grouping/group-by-area.directive.ts
> +            if (this.grid.columnList.find(c => c === column).index < 0) {
```suggestion
            if (this.grid.columnList.find(c => c === column)) {

```
The old code was testing if the column is in the grid column collection, not its index

2021-11-10 12:47 UTC, rkaraivanov approved these changes

2021-11-10 12:48 UTC, merged