Collapse expanded panels when setting singleBranchExpand to true
IgniteUI/igniteui-angular pull request #10652
Opened 2021-11-29 14:35 UTC by mmart1n

Closes #10509   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-11-30 07:08 UTC, wnvko requested changes
Setting `singleBranchExpand` to true is collapsing all panels except the disabled ones. What should happen if at this point you enable given panel - should it collapse or the other expanded panel should collapse?

2021-11-30 08:41 UTC, mmart1n commented
> Setting `singleBranchExpand` to true is collapsing all panels except the disabled ones. What should happen if at this point you enable given panel - should it collapse or the other expanded panel should collapse?

We haven't discussed this case yet. @StefanIvanov Any recommendations?

2021-11-30 08:55 UTC, StefanIvanov commented
@mmart1n yes I think we should leave the handling to the developer since the described case by @wnvko is possible only via the API, there is no scenario that I can come up with happening via direct user interaction.

2021-11-30 09:06 UTC, wnvko submitted a review, later dismissed

2021-12-01 07:30 UTC, kdinev approved these changes

2021-12-01 07:30 UTC, kdinev commented on projects/igniteui-angular/src/lib/accordion/accordion.component.ts
> +                p.cdr.detectChanges();
One call to `cdr.detectChanges()` after collapsing all panels would be better than calling `detectChanges()` on each collapsed panel. Don't reference each expansion panel `cdr` but instead call detectChanges on a cdr from the accordion itself after the `forEach` loop.

2021-12-01 07:35 UTC, kdinev requested changes

2021-12-01 07:35 UTC, kdinev commented on projects/igniteui-angular/src/lib/accordion/accordion.component.ts
> +                p.cdr.detectChanges();
One call to `cdr.detectChanges()` after collapsing all panels would be better than calling `detectChanges()` on each collapsed panel. Don't reference each expansion panel `cdr` but instead call detectChanges on a cdr from the accordion itself after the `forEach` loop.

2021-12-01 09:30 UTC, kdinev requested changes

2021-12-01 09:30 UTC, kdinev commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts
> +    constructor(public cdr: ChangeDetectorRef, protected builder: AnimationBuilder, private elementRef?: ElementRef) {
You can move this back to `private`

2021-12-01 09:30 UTC, kdinev commented on projects/igniteui-angular/src/lib/accordion/accordion.component.ts
> +            this.cdr.detectChanges();
Here you still run `detectChanges()` on every iteration. Move it outside of the `forEach` loop so it's ran once after all iterations.

2021-12-01 09:47 UTC, kdinev approved these changes

2021-12-01 10:45 UTC, merged