feat(tooltip): add tooltip input for showing plain string #10100
IgniteUI/igniteui-angular pull request #10756
Opened 2021-12-21 10:03 UTC by zhosti

Closes #10100   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-12-21 10:51 UTC, gedinakova requested changes
Add tests covering the new functionality.

2021-12-21 15:41 UTC, gedinakova approved these changes

2021-12-21 16:43 UTC, DiyanDimitrov commented
If this is a new feature maybe we should target `master` instead of `13.0.x`.

2022-01-04 10:03 UTC, gedinakova approved these changes

2022-01-04 14:45 UTC, merged