Update bootstrap typography
IgniteUI/igniteui-angular pull request #10906
Opened 2022-01-25 15:03 UTC by desig9stein

Closes #10841 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-01-26 10:11 UTC, StefanIvanov requested changes
Could you also make the h6 to have font width 500?

2022-01-26 10:11 UTC, StefanIvanov commented on projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
> +            description: 'body-2',
```suggestion
            description: 'body-1',
```

2022-01-26 10:11 UTC, StefanIvanov commented on projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
> +
```suggestion
```
should be body 2 as in the default theme

2022-01-26 10:11 UTC, StefanIvanov commented on projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
> +            select-item: 'body-2'
```suggestion
            header: 'body-1',
            item: 'body-1',
            select-item: 'body-1'
```

2022-01-26 12:51 UTC, StefanIvanov approved these changes

2022-01-27 13:42 UTC, simeonoff approved these changes

2022-01-27 15:55 UTC, merged