fix:(input-group) fluent theme input focus styles
IgniteUI/igniteui-angular pull request #11150
Opened 2022-03-02 13:27 UTC by desig9stein

Closes #11145

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-03-02 15:54 UTC, StefanIvanov requested changes
You also need to update the caret color on focus from primary 500 to grays 900

2022-03-02 16:42 UTC, desig9stein commented
> 

Feel free to update the issue with all the required changes. I will fix them all with this PR

2022-03-04 10:29 UTC, StefanIvanov approved these changes

2022-03-08 08:15 UTC, simeonoff approved these changes

2022-03-08 08:21 UTC, simeonoff commented
Actually, the styles differ from the reference implementation in Fluent UI. The focused styles are achieved using border and not box-shadow. The box shouldn't visibly grow on hover/focus. Please, take a look at how the design is implemented in the Ignite UI for Web Components.

2022-03-09 07:58 UTC, merged