style(switch): add switch track-on hover color and styles
IgniteUI/igniteui-angular pull request #11186
Opened 2022-03-08 09:34 UTC by didimmova

Closes #11130 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-03-08 10:31 UTC, StefanIvanov requested changes

2022-03-08 10:31 UTC, StefanIvanov commented on projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_switch.scss
> +            color: ('primary', 900)
```suggestion
            color: ('primary', 800)
```

2022-03-08 10:31 UTC, StefanIvanov commented on projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_switch.scss
> +            color: ('primary', 900)
also update the border-on-hover-color: to ('primary', 800)

2022-03-08 10:31 UTC, StefanIvanov commented on projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_switch.scss
> +        color: ('primary', 100)
```suggestion
        color: ('primary', 200)
```

2022-03-08 10:31 UTC, StefanIvanov commented on projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_switch.scss
> +        color: ('primary', 100)
also update the border-on-hover-color: to ('primary', 200)

2022-03-08 14:55 UTC, StefanIvanov commented
@didimmova you noticed the comments I left to update the border-on-hover-color: as well, didn't you? They should use the same colors as track-on-hover-color: for the respective theme variants

2022-03-09 07:57 UTC, simeonoff submitted a review, later dismissed

2022-03-09 15:34 UTC, StefanIvanov approved these changes

2022-03-09 16:27 UTC, closed without merging