fix(date-time-editor): increment/decrement date portions with arrow up/down keys in shadow DOM
IgniteUI/igniteui-angular pull request #11554
Opened 2022-05-16 10:42 UTC by viktorkombov

Closes #11410 

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-05-17 12:36 UTC, jackofdiamond5 requested changes

2022-05-18 10:51 UTC, jackofdiamond5 approved these changes

2022-05-18 12:22 UTC, jackofdiamond5 commented on projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
> +    if (this.document.activeElement === this.nativeElement ||
PS since this is a bug fix we should add a comment with the following `<initials> <date> <Issue Number|Issue Link> <Comment for the change>`.

2022-05-20 06:55 UTC, jackofdiamond5 approved these changes

2022-05-20 07:47 UTC, Lipata approved these changes

2022-05-20 09:48 UTC, merged