Grid should correctly activate node when loses focus and regain it again
IgniteUI/igniteui-angular pull request #11705
Opened 2022-06-10 10:00 UTC by ddincheva

Closes #11395  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-06-21 07:15 UTC, hanastasov commented
Seems to me that first time I do the steps it is ok, then it starts reproducing again constantly.

2022-06-21 07:15 UTC, hanastasov requested changes
Still reproduces after first try.

2022-06-21 07:29 UTC, Volen99 commented
After testing, the bug still reproduces
![Animation](https://user-images.githubusercontent.com/41373491/174741562-e3938133-7263-41e5-9b79-c204b9d1d28c.gif)
s

2022-08-12 07:15 UTC, hanastasov approved these changes

2022-08-12 07:15 UTC, merged