fix(charts): negative brushes color
IgniteUI/igniteui-angular pull request #11722
Opened 2022-06-16 06:49 UTC by desig9stein

Closes #11662 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-06-16 06:56 UTC, simeonoff approved these changes

2022-06-16 06:56 UTC, simeonoff approved these changes

2022-06-17 13:14 UTC, damyanpetev requested changes

2022-06-17 13:14 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_category-chart.scss
> +/// @property {Color} marker-outlines [hsl(347, 82%, 64%)] - Defines the palette from which automatically assigned series marker outline colors are selected.
This is marker outlines, guessing it should be on negative brushes?

2022-06-17 13:14 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_category-chart.scss
> +/// @property {Color} negative-outlines [hsl(347, 82%, 64%)] - Defines the brushes used for drawing negative elements in a chart type with contextual coloring, such as Waterfall.
Also not sure this affects your SASS docs generation, but if it does - negative brushes/outlines (as the names suggest) are still lists. We're just setting a singular value in them by default, right?

2022-06-20 08:32 UTC, simeonoff approved these changes

2022-06-20 08:40 UTC, merged