fix(schematics): use first project if not available default one
IgniteUI/igniteui-angular pull request #11780
Opened 2022-06-28 12:23 UTC by Lipata

Closes #11761 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-07-15 14:39 UTC, Lipata commented
@kdinev now `ng add` is adding `igniteui-angular` configurations to all the available projects in the app.  This change is also available in 14.0.x branch and require the following changes in the `igniteui-cli`: https://github.com/IgniteUI/igniteui-cli/pull/1048.

2022-07-18 10:19 UTC, kdinev requested changes

2022-07-18 10:19 UTC, kdinev commented on projects/igniteui-angular/schematics/ng-add/add-normalize.ts
> +        if (addPackage) {
I believe this should be outside of the projects forEach loop.

2022-07-18 10:19 UTC, kdinev commented on projects/igniteui-angular/schematics/utils/dependency-handler.ts
> +                    addPackageToPkgJson(tree, pkg, version, entry.target);
Again, shouldn't the `package.json` update be outside of the loop?

2022-07-19 14:25 UTC, kdinev approved these changes

2022-07-19 20:52 UTC, merged