fix(combo): selectable unique falsy values #11610
IgniteUI/igniteui-angular pull request #11859
Opened 2022-07-14 12:51 UTC by kdinev

Closes #11610   
Related #10952 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-07-15 12:12 UTC, wnvko commented
should we make this work and with array of primitive values, e.g. `combo.data = [ null, false, true, '', 0, undefined]`?

2022-07-15 12:27 UTC, wnvko submitted a review, later dismissed

2022-07-19 11:43 UTC, wnvko requested changes

2022-07-19 11:43 UTC, wnvko commented on projects/igniteui-angular/src/lib/combo/combo.common.ts
> +        const isNaNvalue = (key: any): boolean => (isNaN(key) && key !== undefined && typeof key !== 'string') ?? false;
no need to fallback to `false` when `(isNaN(key) && key !== undefined && typeof key !== 'string')` returns `false`.

2022-07-19 11:43 UTC, wnvko commented on projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> +        }
do not proceed with selection update when `newSelection` is same as `oldSelection`.

2022-07-19 15:12 UTC, wnvko approved these changes

2022-07-19 15:35 UTC, jackofdiamond5 approved these changes

2022-07-20 07:39 UTC, merged