Query Builder Component
IgniteUI/igniteui-angular pull request #11960
Opened 2022-08-09 14:00 UTC by mtsvyatkova

Closes #11750 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [X] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-09-27 14:10 UTC, ChronosSF requested changes
Please add the following:
- README about the component in the component's folder
- Modify the overall readme to include this component in the component grid
- Changelog entry

2022-09-27 14:10 UTC, ChronosSF commented on projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
> +    public ngAfterViewInit(): void {
this should also be hidden internal

2022-09-28 11:45 UTC, didimmova commented
@simeonoff 

<img width="436" alt="Screenshot 2022-09-28 at 14 39 15" src="https://user-images.githubusercontent.com/45598235/192769678-22a9eedb-a813-43a6-9fff-b8d986b70b0c.png">
- Buttons are not aligned with the fields

<img width="289" alt="Screenshot 2022-09-28 at 14 41 06" src="https://user-images.githubusercontent.com/45598235/192770033-1f829476-4b8b-4733-b9ae-1589494c8624.png">
- The icon in the igx-prefix also seems to be misaligned

2022-09-28 14:33 UTC, simeonoff commented
> @simeonoff
> 
> <img alt="Screenshot 2022-09-28 at 14 39 15" width="436" src="https://user-images.githubusercontent.com/45598235/192769678-22a9eedb-a813-43a6-9fff-b8d986b70b0c.png">
> 
> -Buttons are not aligned with the fields
> <img alt="Screenshot 2022-09-28 at 14 41 06" width="289" src="https://user-images.githubusercontent.com/45598235/192770033-1f829476-4b8b-4733-b9ae-1589494c8624.png">
> 
> -The icon in the igx-prefix also seems to be misaligned

These must be preexisting issues, as I've not done any modifications to the theme that could introduce them. I suggest we log them as separate issues and fix in another PR so that this one doesn't get dragged any further.

2022-09-29 10:21 UTC, didimmova submitted a review, later dismissed

2022-10-03 07:13 UTC, ChronosSF approved these changes

2022-10-03 12:23 UTC, merged