chore(grid): expose interfaces for the context of template guards
IgniteUI/igniteui-angular pull request #12275
Opened 2022-11-07 16:25 UTC by dkamburov

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-11-14 09:52 UTC, MayaKirova approved these changes

2022-11-16 14:27 UTC, damyanpetev requested changes

2022-11-17 12:16 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/grids/public_api.ts
> +    IgxHeadSelectorTemplateContext, IgxSummaryTemplateContext, GridType, HierarchicalGridType, TreeGridType, PivotGridType
Actually, might be better if we skip exposing grid type(s) for the moment if we can. I'll log a separate issue to sort those out.

2022-11-17 17:28 UTC, damyanpetev approved these changes

2022-11-18 09:09 UTC, merged