Autocomplete Japanese input support for Chrome on Mac
IgniteUI/igniteui-angular pull request #12328
Opened 2022-11-17 13:08 UTC by valadzhov

Closes #11988   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-11-17 15:19 UTC, kdinev requested changes

2022-11-17 15:19 UTC, kdinev commented on projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts
> +        fit('Should accept Japanese input', fakeAsync(() => {
You have a leftover `fit`

2022-11-21 11:01 UTC, Lipata submitted a review, later dismissed

2022-11-21 11:06 UTC, Lipata approved these changes

2022-11-21 12:10 UTC, merged