fix(pivotGrid): Apply dimension with to pivot calcWidth.
IgniteUI/igniteui-angular pull request #12448
Opened 2022-12-12 12:58 UTC by skrustev

Closes #12413

Note: In some cases here the width of the pivot grid is not specified and the parent container doesn't have width the grid sizes to its minimum which imo is valid case but let me know if its ok.
This completely removes the cycle of recalculating the grid size until it decides it can no longer be sized bugger though.

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2022-12-13 09:12 UTC, mddragnev commented
@skrustev If you use the sample from the issue and you remove the min-width on the grid then the grid continues to shrink to where the display container of the cells is around 0px width and then jumps back to the initial width.

2023-01-18 11:23 UTC, kdinev requested changes

2023-01-18 11:23 UTC, kdinev commented on projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
> +        [style.height.px]='totalHeight' [style.width.px]='pivotContentCalcWidth || null' #tbody [attr.aria-activedescendant]="activeDescendant">
@skrustev Change template values to be double-quoted please.

2023-01-24 15:52 UTC, dkamburov approved these changes

2023-01-24 21:05 UTC, merged