fix(row-pinning): preserve pinned state when editing the primary key
IgniteUI/igniteui-angular pull request #12656
Opened 2023-02-16 09:01 UTC by dobromirts

Closes #12569 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2023-02-23 14:05 UTC, ddincheva commented
When you try to edit a column which is set as primary key from a pinned row an error is thrown:
![Pinned row editing error](https://user-images.githubusercontent.com/34240583/220930349-ebf3fdce-83b1-41da-8505-d530426c2691.gif)

2023-02-27 09:52 UTC, ddincheva commented
With the latest fix, there is little inconsistent behavior in some cases when we edit the cell which is the Primary key the pinned rows are reordered:
![PinningRowReorder](https://user-images.githubusercontent.com/34240583/221531039-f9ba28f7-e9db-43a6-af89-a74cca8d0603.gif)

2023-03-07 13:08 UTC, ddincheva requested changes

2023-03-07 13:08 UTC, ddincheva commented on projects/igniteui-angular/src/lib/grids/api.service.ts
> +                const cellRow = this.grid.getRowByIndex(cell.rowIndex);
why do you need to get the row component .. I believe that all the necessary info used below can be directly accessed from the cell and the edit event args like in the selection below

2023-03-11 11:52 UTC, merged

2023-03-14 08:04 UTC, hanastasov reviewed
1) I used the row pinning dev demo
2) Disable rowEditing, set ID column (the PK) to be visible and editable
3) Pin the first row
4) Edit the value of ID column in the pinned row

Result:
`rowPinning` event is emitted twice. In both emissions, the value of `row` argument is missing - first time it is null, second time it is undefined,

2023-03-14 08:04 UTC, hanastasov commented on projects/igniteui-angular/src/lib/grids/api.service.ts
> +        const eventArgs = this.get_pin_row_event_args(rowID, null , null, false);
Why two null values are passed for the `index` and `row` param? Both are available.

2023-03-14 08:04 UTC, hanastasov commented on projects/igniteui-angular/src/lib/grids/api.service.ts
> +        if (typeof index === 'number') {
It is strange to keep a check checking if index would not be a number. Is this needed if no null is passed as index from the unpin_row method?