feat(grid): sort groups by values count
IgniteUI/igniteui-angular pull request #12734
Opened 2023-03-08 12:53 UTC by Svetloslav15

Closes #11642

This PR fix the issue by exposing a custom sorting strategy for grouping.

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2023-03-08 13:17 UTC, kdinev requested changes

2023-03-08 13:17 UTC, kdinev commented on projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts
> +export class GroupSortingStrategy implements ISortingStrategy {
This actually looks good to me. Rename it to `GroupMemberCountSortingStrategy`

2023-03-08 13:43 UTC, kdinev submitted a review, later dismissed

2023-03-08 13:44 UTC, kdinev commented
@Svetloslav15 Please include a `CHANGELOG.md` entry about the newly exposed grouping strategy.

2023-03-08 14:21 UTC, hanastasov commented
THis PR needs to include UI, waiting for the design by @sdimchevski. @sdimchevski , you can run the dev demos and use the sample with the dummy UI (see comment https://github.com/IgniteUI/igniteui-angular/issues/11642#issuecomment-1460117737) to get a feeling of how this feature would work, if this helps with the UI

2023-03-08 14:26 UTC, kdinev commented
@hanastasov We actually don't need an out-of-the-box UI for this.

2023-03-08 15:43 UTC, kdinev submitted a review, later dismissed

2023-03-09 13:08 UTC, hanastasov commented
> It seems that the new strategy is working as expected in almost all cases, but when I tried to use it in the "Country" column in the sample that demonstrates how the feature works, the groups weren't ordered properly:
> 
> ![sortingstrategyissue1](https://user-images.githubusercontent.com/75325639/223952133-bf566849-02d5-4073-a3ec-1f31d48ac6c8.gif) [ ![sortingstrategyissue1](https://user-images.githubusercontent.com/75325639/223952133-bf566849-02d5-4073-a3ec-1f31d48ac6c8.gif) ](https://user-images.githubusercontent.com/75325639/223952133-bf566849-02d5-4073-a3ec-1f31d48ac6c8.gif) [ ](https://user-images.githubusercontent.com/75325639/223952133-bf566849-02d5-4073-a3ec-1f31d48ac6c8.gif)

It seems the sorting logic in the new strategy needs to be enhacned, I guess it is expected to return the records sorted by the grouped column, in my testing case Country:

![image](https://user-images.githubusercontent.com/14248932/224032427-1c315b44-daf0-4489-ae92-2094cc1a9c54.png)

2023-03-10 12:47 UTC, hanastasov approved these changes

2023-03-10 12:47 UTC, merged