feat(expansion-panel): show tooltip for title and description
IgniteUI/igniteui-angular pull request #12878
Opened 2023-04-10 10:01 UTC by RivaIvanova

Closes #12763   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2023-04-26 08:23 UTC, jackofdiamond5 approved these changes

2023-04-27 05:26 UTC, jackofdiamond5 submitted a review, later dismissed

2023-04-27 10:54 UTC, kdinev requested changes

2023-04-27 10:54 UTC, kdinev commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.directives.ts
> +const getTooltipContent = (element: ElementRef): string => {
Create a base class with this method and extend both directives from this new class.

2023-04-28 13:27 UTC, RivaIvanova commented
@kdinev It is ready, however, the `do not merge` label is due to the mass merge to master https://github.com/IgniteUI/igniteui-angular/pull/12935, and as far as I know we should wait for it before merging PRs to master.

2023-05-02 06:13 UTC, merged