Bringing back deleted avatar size property.
IgniteUI/igniteui-angular pull request #13021
Opened 2023-05-16 13:47 UTC by desig9stein

Closes #13017

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2023-05-16 13:49 UTC, kdinev submitted a review, later dismissed

2023-05-17 07:46 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
> +        --avatar-size: #{sizable(#{rem(40px)}, #{rem(64px)}, #{rem(88px)})};
```suggestion
        $size: map.get($theme, 'size');
        
        --size: #{sizable(
            #{if($size, $size, rem(40px))},
            #{if($size, $size, rem(64px))},
            #{if($size, $size, rem(88px))}
        )};
```

2023-05-17 07:47 UTC, simeonoff requested changes
See suggestion.

2023-05-17 08:24 UTC, simeonoff approved these changes

2023-05-17 08:55 UTC, simeonoff approved these changes

2023-05-17 09:45 UTC, merged