Fix error when pressing backspace in an empty dateTime filter
IgniteUI/igniteui-angular pull request #13129
Opened 2023-06-16 09:03 UTC by onlyexeption

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2023-06-20 07:41 UTC, igdmdimitrov approved these changes

2023-06-23 07:08 UTC, kdinev requested changes

2023-06-23 07:08 UTC, kdinev commented on projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
> +        if (eventArgs === null) {
Check for falsy instead of explicit `null`.

2023-06-23 07:50 UTC, kdinev approved these changes

2023-06-26 10:46 UTC, merged