fix(splitter): improving sizing calculations in percent splitter #13252 - master
IgniteUI/igniteui-angular pull request #13358
Opened 2023-08-04 12:45 UTC by ChronosSF

Closes #13252   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2023-08-07 15:05 UTC, mddragnev commented
There is still ~1 px of orange background (as in the sample) when reproducing the issue. Probably because you are reducing the delta too much when calculating the maximum delta. 
![Screenshot 2023-08-07 at 18 02 16](https://github.com/IgniteUI/igniteui-angular/assets/37667452/8105d593-ac2a-4676-8c6c-d96981011b13)

2023-08-07 15:16 UTC, ChronosSF commented
> There is still ~1 px of orange background (as in the sample) when reproducing the issue. Probably because you are reducing the delta too much when calculating the maximum delta. ![Screenshot 2023-08-07 at 18 02 16](https://user-images.githubusercontent.com/37667452/258843457-8105d593-ac2a-4676-8c6c-d96981011b13.png)

Yeah I noticed but my belief is that it actually comes from imperfection of the percent calculations when the browser tries to render them with subpixel precision combined with the presence of the splitter element. Before the fix, what would happen is that the pane getting enlarged would receive additional size because it didn't take the minimum size of the shrinking panel into account when determining max size during the drag. This made the percentages exceed 100% and all kinds of weird issues coming from that. 

I'd say that if you can't reproduce this with pixel resizing, we can probably leave it as is unless you have other ideas.

2023-08-08 13:46 UTC, ChronosSF commented
As discussed with @MayaKirova , I added flex-grow/shrink for % panes to ensure this doesn't require resize observer.

2023-08-09 07:31 UTC, MayaKirova requested changes

2023-08-09 07:31 UTC, MayaKirova commented on projects/igniteui-angular/src/lib/splitter/splitter-pane/splitter-pane.component.ts
> +        const grow = isAuto || (size as string).endsWith('%') ? 1 : 0;
Could use isPercentageSize, also it should not grow/shrink while it's in the process of being dragged so:

```
const grow = this.isPercentageSize && !this.dragSize ? 1 : 0;
```

2023-08-10 07:01 UTC, dkamburov approved these changes

2023-08-10 07:01 UTC, merged