Update selection changing events
IgniteUI/igniteui-angular pull request #13619
Opened 2023-10-31 16:59 UTC by wnvko

Change the `oldSelection` and `newSelection` properties of both combos selection changing arguments to `oldValue` and `newValue`. Also add `oldSelection` and `newSelection` which should always emit the entire selected items.

Also fixes disappearing combo items in the input string when combo is bound to remote data.

Closes #13595  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2023-11-06 08:52 UTC, kdinev approved these changes

2023-11-06 09:24 UTC, kdinev submitted a review, later dismissed

2023-11-06 14:19 UTC, damyanpetev requested changes

2023-11-06 14:28 UTC, valadzhov commented
This is the result when setting the `valueKey` to `null` and this might be a minor issue:
![image](https://github.com/IgniteUI/igniteui-angular/assets/9549439/a2e3e5c8-ffde-4caa-b500-dc14f260611c)

2023-11-06 15:29 UTC, wnvko commented on projects/igniteui-angular/src/lib/combo/combo.common.ts
> +            return item !== undefined ? item : { [this.valueKey]: key };
done

2023-11-06 16:15 UTC, damyanpetev submitted a review, later dismissed

2023-11-06 17:51 UTC, wnvko commented on projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> +                expect(combo.value).toEqual(['']);
this test makes no sense, but is fixed now.
Single combo with array value...

2023-11-06 17:53 UTC, wnvko commented
> This is the result when setting the `valueKey` to `null` and this might be a minor issue: ![image](https://user-images.githubusercontent.com/9549439/280739817-a2e3e5c8-ffde-4caa-b500-dc14f260611c.png)

this should not be supported.

2023-11-07 08:42 UTC, ChronosSF commented
@wnvko , please fix the conflict

2023-11-07 09:31 UTC, kdinev submitted a review, later dismissed

2023-11-07 12:37 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
>                  expect(combo.displayValue).toEqual([]);
👀 I see we have our work cut out for us

2023-11-07 12:39 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> +            it('should not select null, undefined and empty string in a reactive form with required', fakeAsync(() => {
Excluding the fact the `value` getter is weird, the form control integration actually works (or should) correctly and should be fed single items. Also the test is trying to _not_ select some values so the required validator triggers, no?

2023-11-07 15:32 UTC, damyanpetev approved these changes

2023-11-07 16:02 UTC, merged