fix(*): focus input on label click
IgniteUI/igniteui-angular pull request #13778
Opened 2024-01-04 13:51 UTC by IMinchev64

Closes #13756 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-01-08 10:15 UTC, tishko0 approved these changes

2024-01-08 10:25 UTC, skrustev approved these changes

2024-01-08 13:14 UTC, jackofdiamond5 requested changes
This is a bit of a behavioral change so we may want to update the Changelog as well as the docs of all the components to reflect the new way the components will behave.

2024-01-10 09:38 UTC, jackofdiamond5 approved these changes

2024-01-10 16:03 UTC, merged