fix(calendar): no setting of date if same date is already set
IgniteUI/igniteui-angular pull request #13877
Opened 2024-02-06 13:35 UTC by deyvidnenchev

Closes #  13850

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-02-08 14:55 UTC, GrblackStar approved these changes

2024-02-09 14:21 UTC, kdinev requested changes

2024-02-09 14:21 UTC, kdinev commented on projects/igniteui-angular/src/lib/calendar/calendar-base.ts
> +        if(!selectedDate || selectedDate.getTime() !== value.getTime()){
```suggestion
        if (!selectedDate || selectedDate.getTime() !== value.getTime()) {
```

2024-02-09 14:25 UTC, kdinev submitted a review, later dismissed

2024-02-09 19:01 UTC, pmoleri commented on projects/igniteui-angular/src/lib/calendar/calendar-base.ts
> +        if (!selectedDate || selectedDate.getTime() !== value.getTime()) {
This cast is not correct. The fact that the next line checks for `null/undefined` means that it should have been at least `Date | null | undefined`, but what worries me more is if it's not a Date object the `.getTime()` in the next line will crash.

I think adding a compare method will be safer:
```ts
private selectionEquals(a: unknown, b: unknown): boolean {
   if (a instanceof Date && b instanceof Date) {
       return a.getTime() === b.getTime();
    } else if (Array.isArray(a) && Array.isArray(b)) {
        return a.length === b.length && a.every((v, i) => this.selectionEquals(v, b[i]));
    } else {
        return a === b;
    }
}
```

Also, by looking at the code, it's very probable that the same issue can be reproduced with arrays in multiple selection mode

2024-02-12 10:36 UTC, GrblackStar approved these changes

2024-02-12 21:36 UTC, GrblackStar approved these changes

2024-02-15 13:16 UTC, kdinev commented
@pmoleri Do you reject the fix and should I wait for more changes before merging?

2024-02-15 13:18 UTC, hanastasov commented
Actually what @pmoleri highlighted is logged as a separate issue. This PR also waits for the same fix for range selection calendar. I will set the proper status. still in development.

2024-02-15 13:30 UTC, merged