Themes: Add updated Indigo component themes
IgniteUI/igniteui-angular pull request #14064
Opened 2024-04-05 07:57 UTC by simeonoff

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-04-08 13:42 UTC, SisIvanova requested changes

2024-04-08 13:42 UTC, SisIvanova commented on projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss
> +/// @param {Color} $time-item-size [null] - The height of the time item.
```suggestion
/// @param {Number} $time-item-size [null] - The height of the time item.
```

2024-04-08 13:42 UTC, SisIvanova commented on projects/igniteui-angular/src/lib/splitter/splitter.component.ts
> +     * True by default
It's false by default, isn't it?

2024-04-08 13:42 UTC, SisIvanova commented on projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss
> +    $border-color: null,
You haven't documented all new props, only the $time-item-size

2024-04-08 13:42 UTC, SisIvanova commented on projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
> +        selected-time: 'h4'
You have to list all typography styles related to the time-picker here, not only the one that you want to update. This way the 'header-hour' and the 'time-period' styles won't work in bootstrap theme.

2024-04-08 13:42 UTC, SisIvanova commented on projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
> +        header-hour: 'h5',
Same as bootstrap, you have to add the 'time-period' styles.

2024-04-10 23:04 UTC, andiesm813 commented
**SPLITTER**
I dont know if i'm suppose to leave reviews here, please confirm if not. I think the implementation looks good. I compared it with the handoff specifications.

2024-04-11 07:25 UTC, simeonoff commented
> **SPLITTER** I dont know if i'm suppose to leave reviews here, please confirm if not. I think the implementation looks good. I compared it with the handoff specifications.

Yes, here's a good place.

2024-04-11 11:00 UTC, SisIvanova approved these changes

2024-04-11 15:39 UTC, andiesm813 commented
SPLITTER
I did notice one difference in the CSS of the splitter, when expanders are visible. And that is the size of the splitter. In the CSS it says it's 4px.... but when compared to the expander bar on Figma, they look the same height (and the bar in the handoff is 6px high).... So idk if it's visual effects or what...

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/4f6aaaa9-7cee-4ef5-9756-948427ef22f1)


And if i change the height in the CSS to match the height in Figma (6px), the bar looks way larger than the figma one.... everything is bigger.... and stretched...

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/d52c6cee-40c2-4fbc-ac98-886360639346)

So my point is that if other designers review this, i think the 4px value is making the bar look more similar to the handoff.... When setting the correct size of 6px, it will look larger... So 4px is fine.... Splitter is fine by me ;)

2024-04-11 16:58 UTC, andiesm813 commented
SLIDER
Guys, i made a mistake in the handoff for the DARK theme, so the "--tick-color" and the "--tick-label-color" are incorrect. I've updated the handoff, and here are the correct values:

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/a7909169-d5a2-4c69-a8d6-65cfbeee60b0)

--tick-color: var(--igx-slider-base-track-color, color-mix(in oklch, var(--ig-gray-50-contrast) 20%, transparent));
--tick-label-color: var(--igx-slider-base-track-color, color-mix(in oklch, var(--ig-gray-50-contrast) 60%, transparent));

2024-04-11 17:35 UTC, andiesm813 commented
**SLIDER**
The left and right padding of the thumb label is incorrect for the Indigo theme, and i believe the issue is also present in the other themes. Left and right padding should be 0.5 rem. Please @sdimchevski confirm if this is expected in the other themes as well. Thanks!

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/6f84b0ae-e255-46fe-867d-100f2679c006)

2024-04-11 21:05 UTC, andiesm813 commented
**TIME PICKER**

1. In the dark theme, the text color of the header is different from the handoff. The correct colors would be:
--header-hour-text-color: white
--header-time-period-color: white

2. Picker as Dropdown / Dialog Border Color
In both modes, dropdown or dialog, the picker has a border of 1px. 
The border is already specified in the css (both themes), but since it's 0px it's not showing.

3. Shadows / Elevations
I'm pretty sure that some of these elevations were already fixed for other components, but just in case, please make sure that the elevations are updated.

Modal:
- box-shadow: 0px 0px 12px 0px
- Light theme: grays.900 20%
- Dark theme: black 30%

Dropdown:
- box-shadow: 0px 3px 6px 0px
- Light theme: grays.900 20%
- Dark theme: black 30%

2024-04-11 21:36 UTC, andiesm813 commented
**TREE**
I think all the colors are correctly implemented, and i checked inner paddings, sizes, spacing, etc, and it all looks good.
The only difference i see is that i've added a custom expand icon (arrow / chevron), and it would be great if we could use it, because it would be consistent with the other components where i've specified the usage of custom icons (like calendar picker arrows or carousel buttons).

2024-04-12 10:36 UTC, imincheva commented
> **SLIDER** The left and right padding of the thumb label is incorrect for the Indigo theme, and i believe the issue is also present in the other themes. Left and right padding should be 0.5 rem. Please @sdimchevski confirm if this is expected in the other themes as well. Thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/321727006-6f84b0ae-e255-46fe-867d-100f2679c006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTY1NjAsIm5iZiI6MTcxMjkxNjI2MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjE3MjcwMDYtNmY4NGIwYWUtZTI1NS00NmZlLTg2N2QtMTAwZjI2NzljMDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NThmMjNlZTIwZTc4Y2ExZTRhM2NmZjhhY2QxMDcyYzBkOWZjMTBlMmRlMzIxN2VmN2Y1NjQ0OTM4YTc1NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1nVz0R0AG6uIjPG-P_hqf51cjetulKX2sVo5ZeK1a1U)

This isn't mentioned in the Handoff, so it shouldn't be considered as missed during implementation. The specific requirements, such as min-width, padding etc. should be added, so we all know what the requirements are.

2024-04-12 10:40 UTC, imincheva commented
**Slider:**
- The Thumb Label should be Subtitle 1. Currently it's set to Caption.
- Focus Border should be 3px. Currently, it's 0.125rem (2px)

2024-04-12 12:00 UTC, AnjiManova commented
**Tree**

Light and Dark themes
- Disabled node - when there is a disabled node with a checkbox (it doesn't matter its state (checked/indeterminate/unchecked), it should be disabled as well like the other elements in the node

adding two examples from the implementation for reference
<img width="258" alt="image" src="https://github.com/IgniteUI/igniteui-angular/assets/127843837/e5d1f04e-7f2f-45b1-a628-4510e228e060"> <img width="314" alt="image" src="https://github.com/IgniteUI/igniteui-angular/assets/127843837/a77f23f9-d5dd-480f-a07e-145f0993dd05">

adding two examples from the kit
<img width="420" alt="image" src="https://github.com/IgniteUI/igniteui-angular/assets/127843837/0c02f573-de80-459c-a102-3ffafd5937c8"> <img width="380" alt="image" src="https://github.com/IgniteUI/igniteui-angular/assets/127843837/074a65bf-198e-4270-a46f-70baf80366cd">

2024-04-12 12:46 UTC, didimmova commented
> **SPLITTER** I did notice one difference in the CSS of the splitter, when expanders are visible. And that is the size of the splitter. In the CSS it says it's 4px.... but when compared to the expander bar on Figma, they look the same height (and the bar in the handoff is 6px high).... So idk if it's visual effects or what...
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/321692900-4f6aaaa9-7cee-4ef5-9756-948427ef22f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjYxMTMsIm5iZiI6MTcxMjkyNTgxMywicGF0aCI6Ii84NjA2ODU4Mi8zMjE2OTI5MDAtNGY2YWFhYTktN2NlZS00ZWY1LTk3NTYtOTQ4NDI3ZWYyMmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEyNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNGRlMzNhZDI1OTBiMDliYjc4MzllMjAzYjU2NjcyNzA4YWVjZTAwZjQ2OTU1MzIwYTQxNGZmMWFlMzhkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuyhaqZYjzAX-NDoHvEuqME_v8AuHkq6Ef8f9AOXRrs)
> 
> And if i change the height in the CSS to match the height in Figma (6px), the bar looks way larger than the figma one.... everything is bigger.... and stretched...
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/321693598-d52c6cee-40c2-4fbc-ac98-886360639346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjYxMTMsIm5iZiI6MTcxMjkyNTgxMywicGF0aCI6Ii84NjA2ODU4Mi8zMjE2OTM1OTgtZDUyYzZjZWUtNDBjMi00ZmJjLWFjOTgtODg2MzYwNjM5MzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEyNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOGQ1MTEzMmRkYTY3MmQ5ZWQ4MDk5NDk3NDFkNjAyZmU1M2IyZTVlNTlhZTE3MTRhMDg5NjI4NGJlMDAxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DjdebmNxoQKlMfrUV94f9kQoIKATMdjvZaZ97YqMEgo)
> 
> So my point is that if other designers review this, i think the 4px value is making the bar look more similar to the handoff.... When setting the correct size of 6px, it will look larger... So 4px is fine.... Splitter is fine by me ;)

There's 1px border all around, that's why it's 4 + 2px wide.

2024-04-12 12:57 UTC, imincheva commented
**Time Picker Input:**
- Prefix and Suffix should have 4px paddings. Currently, they are 6px.
- Icons in Prefix, Suffix and Clear should be small, not medium.

**Time Picker:**
- Active Item Background should be 46px in width and 32px in height.
- Buttons don't change their size, when you change the size of the Time Picker.
- Buttons' min-width should be 88px.
- Time Picker columns should be 54px in width.
- Min-width of Time Picker dropdowns don't correspond to the ones set in the handoff.
- Text color in dark mode should be grays.900

2024-04-12 13:16 UTC, AnjiManova commented
> **SPLITTER** I did notice one difference in the CSS of the splitter, when expanders are visible. And that is the size of the splitter. In the CSS it says it's 4px.... but when compared to the expander bar on Figma, they look the same height (and the bar in the handoff is 6px high).... So idk if it's visual effects or what...
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/321692900-4f6aaaa9-7cee-4ef5-9756-948427ef22f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTY2NzAsIm5iZiI6MTcxMjkxNjM3MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjE2OTI5MDAtNGY2YWFhYTktN2NlZS00ZWY1LTk3NTYtOTQ4NDI3ZWYyMmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMjQzNzEwMTcwODlhN2FiNzY5ZDMzMWEzMTBiMjAzOGMzMjQwZWE3OGQxM2M4MDI5NDFmNmViZWM0MmYzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YkTFOcpiL_BmlTvwrWC3YcFZZcwn3WwbjxBpAp185zA)
> 
> And if i change the height in the CSS to match the height in Figma (6px), the bar looks way larger than the figma one.... everything is bigger.... and stretched...
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/321693598-d52c6cee-40c2-4fbc-ac98-886360639346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTY2NzAsIm5iZiI6MTcxMjkxNjM3MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjE2OTM1OTgtZDUyYzZjZWUtNDBjMi00ZmJjLWFjOTgtODg2MzYwNjM5MzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNDcwMzRjNGIxYjI3YTJjZDIwMGIzZjQzYjQzNDM5N2E3MjI2OWE1NmEzZWVkZDllN2Q1YmQ2NWI2Zjg2MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r30td7o19XDcCJVMIWhCirlxZBpaDJPfgykQYl8CFvI)
> 
> So my point is that if other designers review this, i think the 4px value is making the bar look more similar to the handoff.... When setting the correct size of 6px, it will look larger... So 4px is fine.... Splitter is fine by me ;)

The Focused state is not implemented as in @andiesm813's Handoff. If this was already communicated, it should be updated in the Handoff too.

Something else that could be considered is the size of the "arrows." Currently, they are not icons, and their size is 4px; decreasing the size to 3px is closer to the Indigo kit. If this comment is not relevant, please ignore it and consider the Splitter as done and design validated.

2024-04-12 13:29 UTC, didimmova commented
> **Slider:**
> 
> * The Thumb Label should be Subtitle 1. Currently it's set to Caption.
> * Focus Border should be 3px. Currently, it's 0.125rem (2px)

@andiesm813 what about tick label? I can't check it anywhere.

2024-04-12 15:18 UTC, desig9stein commented
@andiesm813
_"Picker as Dropdown / Dialog Border Color"_
I verified that the border is visible both in the dropdown and in the dialog, maybe you are confused since the border is implemented with a box-shadow technique, I have one shadow that mimics a border and one for the actual box-shadow.

_"Shadows / Elevations"_
Those are the elevations used, they are the same as in the handoff.
$light-indigo-elevation-time-picker: (
    modal-elevation: 5,
    dropdown-elevation: 3,
);
$dark-indigo-elevation-time-picker: (
    modal-elevation: 7,
    dropdown-elevation: 2,
);


@imincheva  
_"Buttons don't change their size when you change the size of the Time Picker"_
This is working correctly, maybe you didn't put the --ig-size in the right place.

_"Time Picker Input"_
We don't have such a thing as a time-picker input, it is a normal input group, We maintain consistency by treating the time picker as a standard input group, rather than introducing a separate time-picker input. Any necessary modifications should be logged within the input group component itself. This approach ensures uniformity in appearance and functionality, especially when adjacent to other input elements.

2024-04-12 21:41 UTC, andiesm813 commented
> > **Slider:**
> > 
> > * The Thumb Label should be Subtitle 1. Currently it's set to Caption.
> > * Focus Border should be 3px. Currently, it's 0.125rem (2px)
> 
> @andiesm813 what about tick label? I can't check it anywhere.

I did mention it here https://github.com/IgniteUI/igniteui-angular/pull/14064#issuecomment-2050122547

2024-04-12 21:47 UTC, andiesm813 commented
> @andiesm813 _"Picker as Dropdown / Dialog Border Color"_ I verified that the border is visible both in the dropdown and in the dialog, maybe you are confused since the border is implemented with a box-shadow technique, I have one shadow that mimics a border and one for the actual box-shadow.
> 
> _"Shadows / Elevations"_ Those are the elevations used, they are the same as in the handoff. $light-indigo-elevation-time-picker: ( modal-elevation: 5, dropdown-elevation: 3, ); $dark-indigo-elevation-time-picker: ( modal-elevation: 7, dropdown-elevation: 2, );
> 
> @imincheva _"Buttons don't change their size when you change the size of the Time Picker"_ This is working correctly, maybe you didn't put the --ig-size in the right place.
> 
> _"Time Picker Input"_ We don't have such a thing as a time-picker input, it is a normal input group, We maintain consistency by treating the time picker as a standard input group, rather than introducing a separate time-picker input. Any necessary modifications should be logged within the input group component itself. This approach ensures uniformity in appearance and functionality, especially when adjacent to other input elements.

@desig9stein ok! now i understand why there were duplicated elevations and shadows in the css...

I still see the actual shadows different from the figma.... i know you are using the correct elevation numbers, but were the elevation settings changed? because if you look at the dropdown type, the implemented shadow looks darker than the one in the design.

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/fce81790-a8c4-4a72-9671-da81147f63d3)


And in the dialog mode, not only it looks darker, but it still has a different vertical offset.

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/573a8bb9-7a9c-4bcf-8e0d-343788b5b35b)

2024-04-12 21:52 UTC, andiesm813 commented
I'm sorry if i took a long time to reply... i am not getting notifications from @mentions and i dont know why since they are enabled for this repository :(

2024-04-12 22:04 UTC, andiesm813 commented
**SPLITTER**
The focus state of the bar, for both light and dark modes, as shown in the handoff, has a 68% opacity.... and i suppose if you were focused and hovered, then it would change the opacity to 100%. The implemented focus colors are ok.

2024-04-15 06:17 UTC, didimmova commented
> > > **Slider:**
> > > 
> > > * The Thumb Label should be Subtitle 1. Currently it's set to Caption.
> > > * Focus Border should be 3px. Currently, it's 0.125rem (2px)
> > 
> > 
> > @andiesm813 what about tick label? I can't check it anywhere.
> 
> I did mention it here [#14064 (comment)](https://github.com/IgniteUI/igniteui-angular/pull/14064#issuecomment-2050122547)

I was talking about the typography

2024-04-15 06:49 UTC, didimmova commented
> **Slider:**
> 
> * The Thumb Label should be Subtitle 1. Currently it's set to Caption.
> * Focus Border should be 3px. Currently, it's 0.125rem (2px)

Isn't the thumb label subtitle-2?
<img width="747" alt="Screenshot 2024-04-15 at 9 48 51" src="https://github.com/IgniteUI/igniteui-angular/assets/45598235/6426fff2-7c63-4175-a435-2b1f2bc0ff41">

2024-04-15 08:02 UTC, desig9stein commented
> > @andiesm813 _"Picker as Dropdown / Dialog Border Color"_ I verified that the border is visible both in the dropdown and in the dialog, maybe you are confused since the border is implemented with a box-shadow technique, I have one shadow that mimics a border and one for the actual box-shadow.
> > _"Shadows / Elevations"_ Those are the elevations used, they are the same as in the handoff. $light-indigo-elevation-time-picker: ( modal-elevation: 5, dropdown-elevation: 3, ); $dark-indigo-elevation-time-picker: ( modal-elevation: 7, dropdown-elevation: 2, );
> > @imincheva _"Buttons don't change their size when you change the size of the Time Picker"_ This is working correctly, maybe you didn't put the --ig-size in the right place.
> > _"Time Picker Input"_ We don't have such a thing as a time-picker input, it is a normal input group, We maintain consistency by treating the time picker as a standard input group, rather than introducing a separate time-picker input. Any necessary modifications should be logged within the input group component itself. This approach ensures uniformity in appearance and functionality, especially when adjacent to other input elements.
> 
> @desig9stein ok! now i understand why there were duplicated elevations and shadows in the css...
> 
> I still see the actual shadows different from the figma.... i know you are using the correct elevation numbers, but were the elevation settings changed? because if you look at the dropdown type, the implemented shadow looks darker than the one in the design.
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/322147331-fce81790-a8c4-4a72-9671-da81147f63d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUwMTcsIm5iZiI6MTcxMzE2NDcxNywicGF0aCI6Ii84NjA2ODU4Mi8zMjIxNDczMzEtZmNlODE3OTAtYThjNC00YTcyLTk2NzEtZGE4MTE0N2Y2M2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZjg3ZjdkN2QwN2NlOTIzMDc2OGY3NDYzNmJlOGU5OWE1NzEzYzEzZGEwZmU1M2ZhNTRlMjY1NjhmOWRkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRKQD2X9kUGwXbRNeYxcX0rFIvhnzTH4rlSSKqQuXWY)
> 
> And in the dialog mode, not only it looks darker, but it still has a different vertical offset.
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/322147303-573a8bb9-7a9c-4bcf-8e0d-343788b5b35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUwMTcsIm5iZiI6MTcxMzE2NDcxNywicGF0aCI6Ii84NjA2ODU4Mi8zMjIxNDczMDMtNTczYThiYjktN2E5Yy00YmNmLThlMGQtMzQzNzg4YjViMzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZTIwZDMzNmQ1OWUwNmFlMTc2ZTNhYzU2MzFiMGM1MjcyNWEwZjM2OTk5MmZiNWRiODIzNjI1ZWE1OWI5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FrLQhAfRc5LKNTHThYSz1d_hKehQXDMOD9Rs_fYIQcs)

@andiesm813 I thought that all shadows from the UI kit were in sync with the theming, but apparently, they are not. The elevations in the foundation section of the UI kit have to be in sync with the shadows in the theming package, this should be logged as a separate issue.

2024-04-15 13:28 UTC, AnjiManova commented
> > **Slider:**
> > 
> > * The Thumb Label should be Subtitle 1. Currently it's set to Caption.
> > * Focus Border should be 3px. Currently, it's 0.125rem (2px)
> 
> Isn't the thumb label subtitle-2? <img alt="Screenshot 2024-04-15 at 9 48 51" width="747" src="https://private-user-images.githubusercontent.com/45598235/322379095-6426fff2-7c63-4175-a435-2b1f2bc0ff41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzM2MzksIm5iZiI6MTcxMzE3MzMzOSwicGF0aCI6Ii80NTU5ODIzNS8zMjIzNzkwOTUtNjQyNmZmZjItN2M2My00MTc1LWE0MzUtMmIxZjJiYzBmZjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA5Mjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NzI4ZTBmNmNjZjZiNjcwOWUzODhhZWIwOTlhYTQ2YmZjNDZkZWJkNTYzNWJkOGRiOGQ3YjM3YTg5NjY3NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWVq9sPT2wB1F7E2JuuZfmrO5S3_VvLSX1ccuRROqXw">

It should be Subtitle 2

2024-04-16 09:14 UTC, AnjiManova commented
**Splitter**
All comments are implemented and the Splitter can be set to **done** @andiesm813 validate it.

- [x] Splitter

2024-04-16 09:52 UTC, sbayreva commented
#

>

2024-04-16 09:56 UTC, sbayreva commented
> **Time Picker Input:**
> 
> * Prefix and Suffix should have 4px paddings. Currently, they are 6px.
> * Icons in Prefix, Suffix and Clear should be small, not medium.
> 
> **Time Picker:**
> 
> * Active Item Background should be 46px in width and 32px in height.
> * Buttons don't change their size, when you change the size of the Time Picker.
> * Buttons' min-width should be 88px.
> * Time Picker columns should be 54px in width.
> * Min-width of Time Picker dropdowns don't correspond to the ones set in the handoff.
> * Text color in dark mode should be grays.900

**The following comments should be applied:**

* Prefix and Suffix should have 4px paddings. Currently, they are 6px.
* Icons in Prefix, Suffix and Clear should be small, not medium.
* Min-width of Time Picker dropdowns don't correspond to the ones set in the handoff.
* Text color in dark mode should be grays.900

@desig9stein

2024-04-16 11:53 UTC, AnjiManova commented
> **SLIDER**
> 
> 1. Guys, i made a mistake in the handoff for the DARK theme, so the `--tick-color` and the `--tick-label-color` are incorrect. I've updated the handoff, and here are the correct values:
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/321717760-a7909169-d5a2-4c69-a8d6-65cfbeee60b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzM2MzksIm5iZiI6MTcxMzE3MzMzOSwicGF0aCI6Ii84NjA2ODU4Mi8zMjE3MTc3NjAtYTc5MDkxNjktZDVhMi00YzY5LWE4ZDYtNjVjZmJlZWU2MGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA5Mjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYjgzNGQyYmJhNDY3MDEwY2YyZjQ5NmRiM2E5ODFiMjc4YmVjNDEwYzk1NGFlMjc2Y2VmNDgzYjQwZDMwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lEAFaf71aIHAsXEESYrfAk-_TQQDJvQgQoo-wX3obuI)
> 
> `--tick-color`: white 20% `--tick-label-color`: white 60%
> 
> 2. Label background and text colors are incorrect for the dark theme:
> 
> `--label-background-color`: grays.300 `--label-text-color`: white

This comment is implemented.

2024-04-16 11:54 UTC, AnjiManova commented
> **SLIDER** The left and right padding of the thumb label is incorrect for the Indigo theme, and i believe the issue is also present in the other themes. Left and right padding should be 0.5 rem. Please @sdimchevski confirm if this is expected in the other themes as well. Thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/86068582/321727006-6f84b0ae-e255-46fe-867d-100f2679c006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzM2MzksIm5iZiI6MTcxMzE3MzMzOSwicGF0aCI6Ii84NjA2ODU4Mi8zMjE3MjcwMDYtNmY4NGIwYWUtZTI1NS00NmZlLTg2N2QtMTAwZjI2NzljMDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA5Mjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NThjOWNmOTc2Yjg1MWM5YTY1N2JmYWY2YWQ4MmUyOWIyZDM5YWE2ZWYyYTM0MTZiOGVlMjJlZmRlOTE4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCuiTvApyBLhrLLUaXhVH6RKCv7YzRrbXrAQt7yD1iI)

This is implemented and the paddings are 0.5 rem

2024-04-16 12:00 UTC, AnjiManova commented
> **Slider:**
> 
> * The Thumb Label should be Subtitle 1. Currently it's set to Caption.
> * Focus Border should be 3px. Currently, it's 0.125rem (2px)

The comment is implemented right. The label should be Subtitle 2 (1 is typo) and the Focus border is 0.1875.

2024-04-16 12:09 UTC, AnjiManova commented
The min-width of the Thumb Label in the Handoff is 36px not 40 (implementation 2.5rem)
The height is 22px not 30 (implementation)
The border radius is 3px not 2 (implementation)

@andiesm813 please validate this comment

2024-04-16 12:19 UTC, desig9stein commented
> * Prefix and Suffix should have 4px paddings. Currently, they are 6px.
> * Icons in Prefix, Suffix and Clear should be small, not medium.

@sbayreva I already replied to @imincheva 
We don't have such a thing as a time-picker input, it is a normal input group, We maintain consistency by treating the time picker as a standard input group, rather than introducing a separate time-picker input. Any necessary modifications should be logged within the input group component itself. This approach ensures uniformity in appearance and functionality, especially when adjacent to other input elements. I don't think it is a good idea to change the padding and icon size for the input group in the context of the time picker.

> * Min-width of Time Picker dropdowns don't correspond to the ones set in the handoff.

The problem with the min-width for the dropdown version will go away once we remove the density from the component as we discussed in the daily meeting.

2024-04-16 14:19 UTC, andiesm813 commented
> The min-width of the Thumb Label in the Handoff is 36px not 40 (implementation 2.5rem) The height is 22px not 30 (implementation) The border radius is 3px not 2 (implementation)
> 
> @andiesm813 please validate this comment

Yes! all correct!

2024-04-16 14:42 UTC, andiesm813 commented
> **Text Area**
> 
> Everything looks good with the Text Area. @andiesm813 could validate it and if everything is fine just check it as done in the pr description :)
> 
> * [x]  Text Area

All good regarding this particular theme!

I do have a comment related to the positioning of the resize handle. I will discuss with the designers and if needed, i will log it as a separate issue, since it's present in all themes.

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/931ae35e-f80a-4d97-b1ce-02dc01c0bb16)

2024-04-16 15:25 UTC, andiesm813 commented
@didimmova there is an issue with the splitter in both Light and Dark themes.
See attached gif. The horizontal splitter remains expanded. 

![Splitter_Issue](https://github.com/IgniteUI/igniteui-angular/assets/86068582/c89d8701-6bd4-4ec7-887a-cb8596f2459b)

2024-04-16 15:29 UTC, simeonoff commented
> @didimmova there is an issue with the splitter in both Light and Dark themes. See attached gif. The horizontal splitter remains expanded.
> 
> ![Splitter_Issue](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk) [ ![Splitter_Issue](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk) ](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk) [ ](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk)

This issue is not directly related to the splitter, it actually is caused by the drag and drop directive and should be logged separately.

2024-04-16 15:43 UTC, andiesm813 commented
> The min-width of the Thumb Label in the Handoff is 36px not 40 (implementation 2.5rem) The height is 22px not 30 (implementation) The border radius is 3px not 2 (implementation)
> 
> @andiesm813 please validate this comment

**Those 3 issues are still unresolved.** The rest of the slider looks good! All the other differences were solved! 👌

**Label Height and border radius issue** (difference between design and implementation) shown here:

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/403380ff-7178-41a1-907a-d6abaffb9b60)

**Min-width difference** shown below:

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/3640749e-acaf-49a3-9144-a680c49de862)

2024-04-16 15:45 UTC, andiesm813 commented
> > @didimmova there is an issue with the splitter in both Light and Dark themes. See attached gif. The horizontal splitter remains expanded.
> > ![Splitter_Issue](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk)
> >       
> >         [
> >           
> >         
> >             ![Splitter_Issue](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk)
> >           ](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk)
> >         
> >        [ ![Splitter_Issue](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk) ](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk)
> >       
> >         [
> >           
> >         
> >             ![Splitter_Issue](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk)
> >           ](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTc5ODY5YWZiZmNkZTdlZmNkOWVjMDNmZTZmMmNhYzI3NTY4OTc1Y2MxZTg1YzE1NjgxYzkxMjljZTAzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1Je5fJrqKoqpnM9XSdl6J3AQlM-pQtUAHvROAHBypk)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/86068582/322905131-c89d8701-6bd4-4ec7-887a-cb8596f2459b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE1ODAsIm5iZiI6MTcxMzI4MTI4MCwicGF0aCI6Ii84NjA2ODU4Mi8zMjI5MDUxMzEtYzg5ZDg3MDEtNmJkNC00ZWM3LTg4N2EtY2I4NTk2ZjI0NTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1c [...]

2024-04-16 16:29 UTC, andiesm813 commented
> > > @andiesm813 _"Picker as Dropdown / Dialog Border Color"_ I verified that the border is visible both in the dropdown and in the dialog, maybe you are confused since the border is implemented with a box-shadow technique, I have one shadow that mimics a border and one for the actual box-shadow.
> > > _"Shadows / Elevations"_ Those are the elevations used, they are the same as in the handoff. $light-indigo-elevation-time-picker: ( modal-elevation: 5, dropdown-elevation: 3, ); $dark-indigo-elevation-time-picker: ( modal-elevation: 7, dropdown-elevation: 2, );
> > > @imincheva _"Buttons don't change their size when you change the size of the Time Picker"_ This is working correctly, maybe you didn't put the --ig-size in the right place.
> > > _"Time Picker Input"_ We don't have such a thing as a time-picker input, it is a normal input group, We maintain consistency by treating the time picker as a standard input group, rather than introducing a separate time-picker input. Any necessary modifications should be logged within the input group component itself. This approach ensures uniformity in appearance and functionality, especially when adjacent to other input elements.
> > 
> > 
> > @desig9stein ok! now i understand why there were duplicated elevations and shadows in the css...
> > I still see the actual shadows different from the figma.... i know you are using the correct elevation numbers, but were the elevation settings changed? because if you look at the dropdown type, the implemented shadow looks darker than the one in the design.
> > ![image](https://private-user-images.githubusercontent.com/86068582/322147331-fce81790-a8c4-4a72-9671-da81147f63d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUwMTcsIm5iZiI6MTcxMzE2NDcxNywicGF0aCI6Ii84NjA2ODU4Mi8zMjIxNDczMzEtZmNlODE3OTAtYThjNC00YTcyLTk2NzEtZGE4MTE0N2Y2M2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZjg3ZjdkN2QwN2NlOTIzMDc2OGY3NDYzNmJlOGU5OWE1NzEzYzEzZGEwZmU1M2ZhNTRlMjY1NjhmOWRkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRKQD2X9kUGwXbRNeYxcX0rFIvhnzTH4rlSSKqQuXWY)
> > And in the dialog mode, not only it looks darker, but it still has a different vertical offset.
> > ![image](https://private-user-images.githubusercontent.com/86068582/322147303-573a8bb9-7a9c-4bcf-8e0d-343788b5b35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUwMTcsIm5iZiI6MTcxMzE2NDcxNywicGF0aCI6Ii84NjA2ODU4Mi8zMjIxNDczMDMtNTczYThiYjktN2E5Yy00YmNmLThlMGQtMzQzNzg4YjViMzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZTIwZDMzNmQ1OWUwNmFlMTc2ZTNhYzU2MzFiMGM1MjcyNWEwZjM2OTk5MmZiNWRiODIzNjI1ZWE1OWI5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FrLQhAfRc5LKNTHThYSz1d_hKehQXDMOD9Rs_fYIQcs)
> 
> @andiesm813 I thought that all shadows from the UI kit were in sync with the theming, but apparently, they are not. The elevations in the foundation section of the UI kit have to be in sync with the shadows in the theming package, this should be logged as a separate issue in the theming repo.

@desig9stein The shadows for dropdowns and dialogs were already implemented when we worked in those components. I thought if u used the same elevations, that they would look the same as the implemented components. 
When i reviewed those components the shadows were ok.... in this PR they are not... so i'm guessing you are not using the latest updates made on the PRs where dropdown and dialog were done? is that why you said the shadows are not in sync?
Should i log the issue? if so where... thanks Marin!

2024-04-16 17:34 UTC, didimmova commented
> The min-width of the Thumb Label in the Handoff is 36px not 40 (implementation 2.5rem) The height is 22px not 30 (implementation) The border radius is 3px not 2 (implementation)
> 
> @andiesm813 please validate this comment

I updated it now

2024-04-16 17:51 UTC, andiesm813 commented
> > The min-width of the Thumb Label in the Handoff is 36px not 40 (implementation 2.5rem) The height is 22px not 30 (implementation) The border radius is 3px not 2 (implementation)
> > @andiesm813 please validate this comment
> 
> I updated it now

Thanks @didimmova All comments have been resolved then! :)

2024-04-17 08:14 UTC, desig9stein commented
> > > > @andiesm813 _"Picker as Dropdown / Dialog Border Color"_ I verified that the border is visible both in the dropdown and in the dialog, maybe you are confused since the border is implemented with a box-shadow technique, I have one shadow that mimics a border and one for the actual box-shadow.
> > > > _"Shadows / Elevations"_ Those are the elevations used, they are the same as in the handoff. $light-indigo-elevation-time-picker: ( modal-elevation: 5, dropdown-elevation: 3, ); $dark-indigo-elevation-time-picker: ( modal-elevation: 7, dropdown-elevation: 2, );
> > > > @imincheva _"Buttons don't change their size when you change the size of the Time Picker"_ This is working correctly, maybe you didn't put the --ig-size in the right place.
> > > > _"Time Picker Input"_ We don't have such a thing as a time-picker input, it is a normal input group, We maintain consistency by treating the time picker as a standard input group, rather than introducing a separate time-picker input. Any necessary modifications should be logged within the input group component itself. This approach ensures uniformity in appearance and functionality, especially when adjacent to other input elements.
> > > 
> > > 
> > > @desig9stein ok! now i understand why there were duplicated elevations and shadows in the css...
> > > I still see the actual shadows different from the figma.... i know you are using the correct elevation numbers, but were the elevation settings changed? because if you look at the dropdown type, the implemented shadow looks darker than the one in the design.
> > > ![image](https://private-user-images.githubusercontent.com/86068582/322147331-fce81790-a8c4-4a72-9671-da81147f63d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUwMTcsIm5iZiI6MTcxMzE2NDcxNywicGF0aCI6Ii84NjA2ODU4Mi8zMjIxNDczMzEtZmNlODE3OTAtYThjNC00YTcyLTk2NzEtZGE4MTE0N2Y2M2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZjg3ZjdkN2QwN2NlOTIzMDc2OGY3NDYzNmJlOGU5OWE1NzEzYzEzZGEwZmU1M2ZhNTRlMjY1NjhmOWRkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRKQD2X9kUGwXbRNeYxcX0rFIvhnzTH4rlSSKqQuXWY)
> > > And in the dialog mode, not only it looks darker, but it still has a different vertical offset.
> > > ![image](https://private-user-images.githubusercontent.com/86068582/322147303-573a8bb9-7a9c-4bcf-8e0d-343788b5b35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUwMTcsIm5iZiI6MTcxMzE2NDcxNywicGF0aCI6Ii84NjA2ODU4Mi8zMjIxNDczMDMtNTczYThiYjktN2E5Yy00YmNmLThlMGQtMzQzNzg4YjViMzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZTIwZDMzNmQ1OWUwNmFlMTc2ZTNhYzU2MzFiMGM1MjcyNWEwZjM2OTk5MmZiNWRiODIzNjI1ZWE1OWI5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FrLQhAfRc5LKNTHThYSz1d_hKehQXDMOD9Rs_fYIQcs)
> > 
> > 
> > @andiesm813 I thought that all shadows from the UI kit were in sync with the theming, but apparently, they are not. The elevations in the foundation section of the UI kit have to be in sync with the shadows in the theming package, this should be logged as a separate issue in the theming repo.
> 
> @desig9stein The shadows for dropdowns and dialogs were already implemented when we worked in those components. I thought if u used the same elevations, that they would look the same as the implemented components. When i reviewed those components the shadows were ok.... in this PR they are not... so i'm guessing you are not using the latest updates made on the PRs where dropdown and dialog were done? is that why you said the shadows are not in sync? Should i log the issue? if so where... thanks Marin!

@andiesm813  You should log an issue in the theming repo to sync all elevation from the UI kit with the theming engine.

These are the elevations that we have implemented for the indigo theme. Comparing them to the UI kit I can see that they are not in sync.
<img width="933" alt="Screenshot 2024-04-17 at 10 17 04" src="https://github.com/IgniteUI/igniteui-angular/assets/21260963/996f17b2-b146-41d3-9e56-295010091103">

Indigo Time-picker in dialog mode has different elevations from the dialog component in the UI kit. Inside the UI kit and in the theming the dialog component uses elevation 24 for the light theme and 23 for the dark. Time-picker in dialog mode uses 5 for light and 7 for dark. The indigo dropdown component is not yet implemented, there is an [issue](https://github.com/IgniteUI/igniteui-theming/issues/234) that will be handled next sprint.

2024-04-17 14:48 UTC, andiesm813 commented
**TIME PICKER ELEVATIONS**

@desig9stein i just double checked to make sure that the Time Picker is using the correct elevations.

Currently these are the implemented elevations:

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/a293bc34-82c0-445c-aabc-fec2d58a16bb)

They match the elevations that i have set in Figma as well:

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/4c355577-edc5-4361-8fb6-9c1addf7c57c)

So i can say that the implementation of the Time Picker is correct ✅, and what's not correct are the values inside the elevations. We can fix those separately like you said.

2024-04-18 08:31 UTC, SisIvanova submitted a review, later dismissed

2024-04-18 08:42 UTC, SisIvanova approved these changes

2024-04-18 10:34 UTC, SisIvanova approved these changes

2024-04-19 07:28 UTC, merged