feat(checkbox): complete checkbox refinements
IgniteUI/igniteui-angular pull request #14161
Opened 2024-04-24 12:19 UTC by didimmova

Closes #14107 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-05-08 07:30 UTC, SisIvanova requested changes

2024-05-08 12:36 UTC, SisIvanova submitted a review, later dismissed

2024-05-13 14:10 UTC, imincheva commented
**All themes**
- Tick isn't properly aligned to the center of the checkbox (both for checked and indeterminate state)

**Bootstrap**
- Tick SVG needs to be updated, in order to match the most recent changes in the UI kit (it has been updated, in order to match the official Bootstrap component)
- Tick in all themes (both for checked and indeterminate state) isn't properly aligned to the center of the checkbox
- Invalid unchecked state: when in hover and focused state, the border color isn't linked to the proper variable (--error-color-hover)

2024-05-14 07:49 UTC, imincheva commented
**Fluent**
- Invalid unchecked: the tick color on hover and focused & hover state should be error.500

2024-05-14 08:07 UTC, AnjiManova commented
**Material**

The Active state of the unchecked checkbox in light and dark should be changed. Let's try with the --empty-color and the current opacity.

Everything else looks good.

2024-05-16 06:37 UTC, desig9stein approved these changes

2024-05-16 11:34 UTC, merged