Deprecated properties cleanup
IgniteUI/igniteui-angular pull request #14323
Opened 2024-06-04 08:13 UTC by damyanpetev

Removing long-standing deprecated properties.
Only haven't dropped the backing logic behind the Overlay attach to drop the deprecated factory usage - that can be dropped latter at any point.

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-06-04 09:07 UTC, kdinev requested changes

2024-06-04 09:07 UTC, kdinev commented on projects/igniteui-angular/src/lib/banner/banner.component.ts
> -        this._bannerEvent = { banner: this, owner: this, event};
Since this was never migrated, I believe a migration is necessary.

2024-06-04 14:05 UTC, wnvko approved these changes

2024-06-05 08:37 UTC, wnvko approved these changes
changes in overlay service LGTM

2024-06-05 12:59 UTC, merged