Remove filterable property
IgniteUI/igniteui-angular pull request #14408
Opened 2024-06-18 15:14 UTC by MonikaKirkova

Closes #14340 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [x] This PR contains breaking changes
 - [x] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-06-20 12:42 UTC, Lipata commented
@sdimchevski With this PR in `igniteui-angular` we are always making filtering available and removing the option to enable/disable it. This is a little bit different from what is in `igniteui-webcomponents`, where we have the `disableFiltering` option available.

You can see that in angular [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo-features), disabling the filter will not remove the search input, just will stop the filtering and reduce the list. While in the webcomponent [sample](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/combo/features) when filtering is disabled, then the search input is removed.

On one hand, we want to have consistency between different platforms. On the other hand disabling the filtering may not be a common scenario, but would appreciate any design input from you on the matter.

2024-06-25 12:32 UTC, MonikaKirkova commented on CHANGELOG.md
> +    - **Breaking Change** `filterable` is removed from the `filteringOptions`.
There is a custom migration for the filteringOptions.

2024-06-25 20:04 UTC, Lipata approved these changes

2024-06-26 13:25 UTC, sdimchevski commented
> @sdimchevski With this PR in `igniteui-angular` we are always making filtering available and removing the option to enable/disable it. This is a little bit different from what is in `igniteui-webcomponents`, where we have the `disableFiltering` option available.
> 
> You can see that in angular [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo-features), disabling the filter will not remove the search input, just will stop the filtering and reduce the list. While in the webcomponent [sample](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/combo/features) when filtering is disabled, then the search input is removed.
> 
> On one hand, we want to have consistency between different platforms. On the other hand disabling the filtering may not be a common scenario, but would appreciate any design input from you on the matter.

@Lipata @kdinev From a UX point of view, right now in Angular it’s not OK and is confusing to set filtering disabled and still have the search option. The behavior in Angular is actually the same as in Web components, once you switch off the Allow Custom Values feature (there is no such feature in WebC). So instead of removing the option to enable/disable the filtering in Angular, when we have the filtering disabled and the Allow Custom Values enabled, why don't we change the Placeholder from Search to Add Item?

2024-06-27 11:26 UTC, kdinev commented
> > @sdimchevski With this PR in `igniteui-angular` we are always making filtering available and removing the option to enable/disable it. This is a little bit different from what is in `igniteui-webcomponents`, where we have the `disableFiltering` option available.
> > You can see that in angular [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo-features), disabling the filter will not remove the search input, just will stop the filtering and reduce the list. While in the webcomponent [sample](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/combo/features) when filtering is disabled, then the search input is removed.
> > On one hand, we want to have consistency between different platforms. On the other hand disabling the filtering may not be a common scenario, but would appreciate any design input from you on the matter.
> 
> @Lipata @kdinev From a UX point of view, right now in Angular it’s not OK and is confusing to set filtering disabled and still have the search option. The behavior in Angular is actually the same as in Web components, once you switch off the Allow Custom Values feature (there is no such feature in WebC at the moment). So instead of removing the option to enable/disable the filtering in Angular, when we have the filtering disabled and the Allow Custom Values enabled, why don't we change the Placeholder from Search to Add Item?

I agree with your suggestion and if the placeholder displays the correct prompt, then I'm OK.

2024-07-24 14:41 UTC, MonikaKirkova commented
@sdimchevski, @kdinev Except changing the placeholder, should we remove the `filterable` from the `filteringOptions` and rename the `filterable` property to `disableFiltering` as in the web components.

2024-07-26 14:37 UTC, kdinev commented
> @sdimchevski, @kdinev Except changing the placeholder, should we remove the `filterable` from the `filteringOptions` and rename the `filterable` property to `disableFiltering` as in the web components.

Yes, please do that!

2024-08-06 13:20 UTC, damyanpetev commented
@MonikaKirkova Since we want to have the search placeholder change between filtering & custom value state being enabled, it might not be bad idea to have those placeholders in the `resourceStrings` for the Combo. That's now hardcoded in English in the `@Input() searchPlaceholder`, but since it'll be dynamic I think we should deprecate the input and leave it empty by default.

PS: Talking of localization, there are also string of hardcoded English in the markup like `"Clear Selection"` and `Add item` which should all be localizable and in the resource strings. Could be a separate task ofc for any such strings you find.

2024-08-14 10:44 UTC, Lipata approved these changes

2024-08-19 13:05 UTC, Lipata approved these changes

2024-08-21 12:40 UTC, damyanpetev commented on CHANGELOG.md
> +    - **Breaking Change** The `filterable` property is renamed to `disableFiltering`.
Um, the main breaking is the `filterable` in the `filteringOptions` being removed?
Might not be an easy way to migrate that - depending on usage, should we consider deprecating it instead? ( I know 😑)

IIRC `filterable` was marked as deprecated, so it should have no active usage (hopefully), though that's also breaking, sure.

2024-08-21 13:25 UTC, damyanpetev commented on CHANGELOG.md
> +    - **Breaking Change** The `filterable` property is renamed to `disableFiltering`.
Also, also this should be for 18.2 now?

2024-09-13 15:04 UTC, Lipata approved these changes

2024-09-17 17:02 UTC, damyanpetev requested changes
Mostly the changelog/public API and some parts of the migrations that might need addressing. The rest are comments for now or at least something to discuss.

2024-09-17 17:02 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/core/i18n/combo-resources.ts
>      igx_combo_clearItems_placeholder?: string;
Eh, somewhat assumed this was going to be added with this PR, but instead it went in with #14620 (and propagated back too), so a bit late for this comment:
Do be careful with naming public API - it's not a `addCustomValues_placeholder` if it's also the text of the button, no? So the name should've been more generic or reflective of the use. I do hope that's been communicated so the translation makes sense in both places, though we might very well consider 
Similar for `clearItems_placeholder`.. that's a tooltip or aria label.

---

As for the actual `enabledFilter_placeholder` - could be more descriptive, either filter field or filter search placeholder (to go with the old prop I guess).

2024-09-18 13:50 UTC, damyanpetev commented on projects/igniteui-angular/migrations/update-18_2_0/index.ts
> +        host.overwrite(path, content);
Okay, the extra changes from visitor will drop out with #14787 so at last the potential for conflicting changes and will be left to just the remaining combo stuff.

2024-10-15 16:14 UTC, damyanpetev approved these changes

2024-10-15 16:26 UTC, merged