Allow negative values in filter input
IgniteUI/igniteui-angular pull request #14477
Opened 2024-07-04 14:18 UTC by MonikaKirkova

Closes #14086 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-07-16 11:03 UTC, gedinakova requested changes

2024-07-16 11:03 UTC, gedinakova commented on projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html
> +            type="text"
This is a really major change in the filtering UI which may cause other problems. The number input actually allows typing - & + signs, so the problem seems to be in the filtering logic itself. I believe the problem is in the IgxGridFilteringRowComponent's "onInput event handler. When the target's value is just "-" (or + actually) it is resolved as NaN, hence the behavior you are observing. I sugges we account for this specific scenario by adding something similar to:
public onInput(eventArgs) {
.....
        const target = eventArgs.target;
        if (!target.value && this.column.dataType === GridColumnDataType.Number) {
            return;
        }
        if (this.column.dataType === GridColumnDataType.DateTime) {
          ....

2024-07-19 10:25 UTC, gedinakova commented on projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
> +            if (val === '') {
Doesn't this if eliminate the need of the newly added check in onInput?

2024-07-23 15:54 UTC, ChronosSF commented
Closing this as it will duplicate with the mass merges.

2024-07-23 15:54 UTC, closed without merging