fix(grid): recreate columns when data changes with autoGenerate enabled - master
IgniteUI/igniteui-angular pull request #14493
Opened 2024-07-09 11:39 UTC by georgianastasov

Closes #14315  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-07-17 07:43 UTC, hanastasov requested changes
This fixes it for flat grid, but not for Hierarchical one. Please review all other grids as well.

2024-07-17 08:02 UTC, georgianastasov commented
@hanastasov I've reviewed the other grid structures (tree grid and hierarchical grid) and confirmed that the fix applies identically to them as well.

2024-07-17 13:02 UTC, georgianastasov commented
After a discussion with @hanastasov, it turns out that our initial assumption was correct. The `shouldGenerate` property can be completely removed from all grid structures (grid, tree grid, hierarchical grid and pivot grid). Instead, we can rely solely on the `autoGenerate` property.

Upon reviewing the implementation, we found that the `shouldGenerate` property essentially performs the same function as `autoGenerate`, making it redundant. By removing `shouldGenerate`, we simplify the grid generation process and avoid any confusion.

2024-07-18 07:30 UTC, hanastasov commented
> After a discussion with @hanastasov, it turns out that our initial assumption was correct. The `shouldGenerate` property can be completely removed from all grid structures (grid, tree grid, hierarchical grid and pivot grid). Instead, we can rely solely on the `autoGenerate` property.
> 
> Upon reviewing the implementation, we found that the `shouldGenerate` property essentially performs the same function as `autoGenerate`, making it redundant. By removing `shouldGenerate`, we simplify the grid generation process and avoid any confusion.

In addition to deprecating the `shouldGenerate`:
- setting a value to `shouldGenerate` via the public API should assign the same value to `autoGenerate`, in order to keep customers code working with no behavior changes

2024-07-23 07:27 UTC, MayaKirova approved these changes
I'm fine with the change. Just make sure to test remote scenarios since there the data is changed via the setter.

2024-07-23 07:39 UTC, georgianastasov commented
> I'm fine with the change. Just make sure to test remote scenarios since there the data is changed via the setter.

@MayaKirova Could you tell me a little more specifically what scenarios to test exactly and where? For which component and which file should I focus on? Should I create a new test for this or stay with the current tests and test it locally?

2024-07-23 10:40 UTC, MayaKirova commented
@georgianastasov The things that come to mind are [remote operations](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote-data-operations), like paging, virtualization, sorting, filtering, load on demand etc. 
Also something like the [live data sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/live-data#angular-live-data-update-example)  where the data changes constantly. We really don't want a scenario where "autoGenerate" is enabled and updates on the data cause the grid to constantly keep re-creating the columns.

2024-07-23 13:28 UTC, dkamburov commented on projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
> +    private shouldRegenerateColumns(oldData: any[] | null | undefined, newData: any[] | null | undefined): boolean {
Could've add it as protected in the grid-base and reuse in the three grids instead if repeating it.

2024-07-23 13:58 UTC, dkamburov submitted a review, later dismissed

2024-07-24 13:29 UTC, georgianastasov commented
I have tested all the mentioned scenarios including remote operations (paging, virtualization, sorting, filtering, load on demand), and live data updates where the data changes constantly. I have not encountered any problems, obstacles, or issues. The columns are not recreated in any of these scenarios, as noted. For better verification, someone from our team will also test all scenarios.

2024-07-25 08:34 UTC, ChronosSF commented
@georgianastasov , @MayaKirova , is this going to be included only in the latest branch or is it a fix? All other PRs seem to have been closed.

2024-07-25 08:36 UTC, MayaKirova commented
@ChronosSF It does introduce a breaking change, so it should only go in the latest version IMO.

2024-07-25 09:36 UTC, ChronosSF requested changes

2024-07-25 09:36 UTC, ChronosSF commented on projects/igniteui-angular/migrations/update-18_1_0/changes/members.json
>              ]
Since 18.1 is already released these migrations should be moved to a 18.2 migration

2024-07-25 12:59 UTC, ChronosSF commented
Adding do-not-merge so that we can have the mass merges for more time. We'll merge this once a few more new features line up for being added to master.

2024-07-25 13:01 UTC, dkamburov submitted a review, later dismissed

2024-07-25 14:05 UTC, ChronosSF submitted a review, later dismissed

2024-08-26 10:32 UTC, hanastasov approved these changes

2024-08-26 15:49 UTC, merged