Fixed header height issue for grouped headers
IgniteUI/igniteui-angular pull request #14621
Opened 2024-08-12 14:27 UTC by MarielaTihova

Resolves #14424 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-08-22 11:14 UTC, skrustev requested changes

2024-08-22 11:14 UTC, skrustev commented on projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
> +        fit('should initialize a grid with correct header height', () => {
Leftover `fit` i guess

2024-08-26 15:05 UTC, MarielaTihova commented on projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
> +        fit('should initialize a grid with correct header height', () => {
Resolved with commit [529d4c69d3bfdf923e0e84ad9ae26f91e2156cb1](https://github.com/IgniteUI/igniteui-angular/pull/14621/commits/529d4c69d3bfdf923e0e84ad9ae26f91e2156cb1)

2024-09-18 07:25 UTC, dkamburov commented
@MarielaTihova supported versions are 17.2, 18.1 and master. Please create pr for them as well or this is only reproducible in 18.1?

2024-09-18 14:05 UTC, MarielaTihova commented
> @MarielaTihova supported versions are 17.2, 18.1 and master. Please create pr for them as well or this is only reproducible in 18.1?

Created a PR for master as discussed: [Fixed header height issue for grouped headers](https://github.com/IgniteUI/igniteui-angular/pull/14788)

2024-10-28 12:03 UTC, closed without merging