feat(carousel): align with WC carousel
IgniteUI/igniteui-angular pull request #14651
Opened 2024-08-20 14:23 UTC by RivaIvanova

Closes #14627   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [x] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [x] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-09-17 13:13 UTC, yradoeva commented
**Probably a bug - valid for all themes, light & dark**

**Focus gets lost from the indicators' container when changing slides with the keyboard**
Steps to reproduce:
1. Open the carousel component (keyboardSupport is on)
2. Focus with the Tab/Shift+Tab the indicators' container
3. Press keyboard arrow left/right to change slide

Result:
Focus gets lost

Expected result:
The focus stays on the indicators' container when navigating with the keyboard buttons between slides.

https://github.com/user-attachments/assets/4062591d-9876-4603-9bee-908e91f90f97

2024-09-24 12:55 UTC, simeonoff submitted a review, later dismissed

2024-09-26 06:23 UTC, rkaraivanov requested changes
LGTM, just a tiny issue in the changelog.

2024-09-26 06:23 UTC, rkaraivanov commented on CHANGELOG.md
> +
Technically, this should be a deprecation since we have not removed it yet, right?

2024-09-26 08:19 UTC, rkaraivanov approved these changes

2024-09-26 08:19 UTC, merged