feat(demos): add compared to WC section with samples to compare components
IgniteUI/igniteui-angular pull request #14813
Opened 2024-09-24 05:12 UTC by didimmova

Closes #14764

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [x] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2025-01-10 13:12 UTC, simeonoff commented on src/app/stepper-showcase/stepper-showcase.sample.ts
> +    IgxStepType,
Use the IGX_STEPPER_DIRECTIVES when importing stepper-related components.

2025-01-10 13:13 UTC, simeonoff commented on src/app/tabs-showcase/tabs-showcase.sample.ts
> +    IgxTabsComponent
Use the IGX_TABS_DIRECTIVES when importing tab-related components.

2025-01-10 13:15 UTC, simeonoff commented on src/app/tree-showcase/tree-showcase.sample.html
> +        [style.--ig-size]="'var(--ig-size-' + properties.size + ')'"
Use the proposed IgSize directive when setting the size of the component here.

2025-01-10 13:16 UTC, simeonoff commented on src/app/tree-showcase/tree-showcase.sample.html
> +        [style.--ig-size]="'var(--ig-size-' + properties.size + ')'"
Use the proposed IgSize directive when setting the size here.

2025-01-10 13:16 UTC, simeonoff commented on src/app/tree-showcase/tree-showcase.sample.html
> +                                    </ng-container>
Use the new control flow syntax.

2025-01-10 13:17 UTC, simeonoff commented on src/app/tree-showcase/tree-showcase.sample.ts
> +import { IgxTreeComponent, IgxTreeNodeComponent, IgxTreeSelectionType } from 'igniteui-angular';
Use the IGX_TREE_DIRECTIVES when importing tree-related components.

2025-01-10 13:18 UTC, simeonoff commented on src/app/tree-showcase/tree-showcase.sample.ts
> +    };
Use an actual Map object.

2025-01-10 13:44 UTC, simeonoff commented on src/app/tree-showcase/tree-showcase.sample.ts
> +        this.data = cloneDeep(HIERARCHICAL_SAMPLE_DATA);
You should be able to use the native structuredClone method in place of deepClone function from lodash here.

2025-01-14 07:43 UTC, didimmova commented on src/app/calendar/calendar.sample.ts
> +    DateRangeType,
these are not contained in the IGX_DATE_RANGE_PICKER_DIRECTIVES

2025-01-17 07:34 UTC, simeonoff requested changes

2025-01-17 07:40 UTC, simeonoff commented on src/app/slider-showcase/slider-showcase.sample.html
> +<!-- TODO: Slider tick have different floating number formating -->
@desig9stein

2025-01-17 12:25 UTC, simeonoff commented on projects/igniteui-angular/src/lib/directives/size/ig-size.directive.ts
> +    }
Why did you decide to go this route? In my opinion having the input match the name of the getter setter is a lot more straight-forward. Plus, you can still limit what the input type can be via the setter's value type as described in my previous review comments.

2025-01-17 12:25 UTC, simeonoff commented on src/app/card/card.sample.ts
> +    standalone: true,
No longer necessary with angular 19+. True is the default option.

2025-01-17 12:27 UTC, simeonoff commented on src/app/app.component.html
>          <ng-template *ngIf="drawerState.miniVariant" igxDrawerMini>
@didimmova This still uses the old control flow syntax.

2025-01-17 14:52 UTC, simeonoff approved these changes

2025-01-17 14:53 UTC, merged