feat(query-builder): add public api for commit and discard current state
IgniteUI/igniteui-angular pull request #14910
Opened 2024-10-15 08:32 UTC by igdmdimitrov

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-10-15 09:38 UTC, gedinakova commented
@igdmdimitrov Currently, if I edit a condition in a subquery, it would commit the inner condition only. Nothing happens for the parent condition:
![image](https://github.com/user-attachments/assets/fe14d537-971c-4f09-a0b0-0568c4150e53)
On commit, the result is:
![image](https://github.com/user-attachments/assets/e03f2f3c-b6b9-4e22-990c-fa2cc8fee87f)
Even if I commit at this point, the parent condition is not committed.

2024-10-15 13:36 UTC, gedinakova requested changes

2024-10-15 13:36 UTC, gedinakova commented on projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> +        it('canCommit should return the correct validity state of curently edited condition.', fakeAsync(() => {
```suggestion
        it('canCommit should return the correct validity state of currently edited condition.', fakeAsync(() => {
```

2024-10-15 13:36 UTC, gedinakova commented on projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> +            fix.detectChanges();
Do we need this second change detection?

2024-10-15 13:36 UTC, gedinakova commented on projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> +            // Verify the Query Builder validity state while editin a condition.
```suggestion
            // Verify the Query Builder validity state while editing a condition.
```

2024-10-15 13:36 UTC, gedinakova commented on projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> +        }));
Please add a couple tests covering the scenario where we actually commit an invalid condition and check it doesn't throw.

2024-10-16 06:37 UTC, gedinakova requested changes

2024-10-16 06:37 UTC, gedinakova commented on projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> +        it(`Should NOT throw errors when an invalid condition is commited through API.`, fakeAsync(() => {
```suggestion
        it(`Should NOT throw errors when an invalid condition is committed through API.`, fakeAsync(() => {
```

2024-10-16 06:37 UTC, gedinakova commented on projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> +            expect(console.error).not.toHaveBeenCalled();
Add a check what actually was committed.

2024-10-16 06:39 UTC, gedinakova requested changes
We need a test with subQuery - verify that both the inner & the parent condition are committed (we actually had a bug initially).

2024-10-16 10:48 UTC, teodosiah commented
1. Change the entity in the nested query
2. Commit through API
![QB_issue12](https://github.com/user-attachments/assets/3b58b4c2-94df-4939-9c44-f95a37161d0a)
The empty expression is still in edit mode

2024-10-16 10:53 UTC, teodosiah commented
If we clear the return fields and commit through API as follows:
![QB_issue13](https://github.com/user-attachments/assets/17097b87-569e-44e8-a417-d261a05e56ed)
We would have 
![image](https://github.com/user-attachments/assets/7ac7e111-14cf-40c3-a752-1fa647d37939)
@imincheva  Should we change the appearance in this scenario in order to notify the user that this is not a valid expression?

2024-10-16 11:02 UTC, teodosiah commented
- If we commit through API an expression with a column of type number without selecting operator the chip looks like the following:

![image](https://github.com/user-attachments/assets/6adfff3f-32dd-4b4d-9556-214a76c75c69)

- For other data types the chip in this scenario will be the following:
![image](https://github.com/user-attachments/assets/69fdb8de-08ef-4061-a59a-a9db9056fa7f)

However, there is a valid Null operator that could be chosen and the chip would be the same:
![image](https://github.com/user-attachments/assets/0e927437-981b-45df-a90e-2ebb3efa00ad)

@imincheva Do you have any suggestions how we should mark such invalid expressions once they are committed (through API), so they look similar regardless of their column data type and not the same as some valid expression?

2024-10-17 07:27 UTC, gedinakova commented
An error is thrown on attempting to commit an inner query without conditions:
![image](https://github.com/user-attachments/assets/8c038ded-2e54-462a-a454-7fbaacbe5f29)
![image](https://github.com/user-attachments/assets/355e6b14-7b9a-4859-86c6-d22698b6d540)

2024-10-23 14:22 UTC, gedinakova approved these changes

2024-10-25 06:37 UTC, gedinakova commented
> * If we commit through API an expression with a column of type number without selecting operator the chip looks like the following:
> 
> ![image](https://private-user-images.githubusercontent.com/52423497/377021027-6adfff3f-32dd-4b4d-9556-214a76c75c69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mzg0MzQsIm5iZiI6MTcyOTgzODEzNCwicGF0aCI6Ii81MjQyMzQ5Ny8zNzcwMjEwMjctNmFkZmZmM2YtMzJkZC00YjRkLTk1NTYtMjE0YTc2Yzc1YzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2MzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOGMyMjc2MGE4NGMzZTljZjNmYjNiODE0MzAxYjZmMTZjNTZjYzJhOTc1ZDQ5ZTdkOGY1M2Q2YjQ2YzRjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y2fZXeK9Y3mtXK4A0Tqj3eEV6Fm-uKPLifZkdmK6fks)
> 
> * For other data types the chip in this scenario will be the following:
>   ![image](https://private-user-images.githubusercontent.com/52423497/377021343-69fdb8de-08ef-4061-a59a-a9db9056fa7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mzg0MzQsIm5iZiI6MTcyOTgzODEzNCwicGF0aCI6Ii81MjQyMzQ5Ny8zNzcwMjEzNDMtNjlmZGI4ZGUtMDhlZi00MDYxLWE1OWEtYTlkYjkwNTZmYTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2MzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MTlmMzllOWEzZmIwZWU5NWNjMjJiODkwNTBiMDVjMTJkNjAwODc0YWE0ODU5NzI2Mjc2NGQ5MDdkODBkZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nMxOQU5WTBoabXDi9LzHQiAuIEu_yWeUTkaHbBArzGs)
> 
> However, there is a valid Null operator that could be chosen and the chip would be the same: ![image](https://private-user-images.githubusercontent.com/52423497/377021838-0e927437-981b-45df-a90e-2ebb3efa00ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mzg0MzQsIm5iZiI6MTcyOTgzODEzNCwicGF0aCI6Ii81MjQyMzQ5Ny8zNzcwMjE4MzgtMGU5Mjc0MzctOTgxYi00NWRmLWE5MGUtMmViYjNlZmEwMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2MzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNTg0MGQ4OTBmM2VkM2QzMjQ5OTMzNjdkNGU2NDBkZjliMjcwNWE0NjE0MTU2NzYxZTdjZjYyMjQwYjA4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O80wshiwhCHQeVF8kZGYl-31GHe58ERbu98PFs1722s)
> 
> @imincheva Do you have any suggestions how we should mark such invalid expressions once they are committed (through API), so they look similar regardless of their column data type and not the same as some valid expression?

A decision was taken to throw an error on attempting to commit invalid state instead of going into too many weird scenarios after committing an invalid condition.

2024-10-25 06:52 UTC, gedinakova commented
@igdmdimitrov 
1. In the dev demo, modify any existing condition by deleting the search value
2. Exit edit mode on the editor

Result: The "commit" button stays enabled. canCommit() returns true.
![image](https://github.com/user-attachments/assets/442ed9c8-ea1a-4efb-9692-1faede6137ed)


Note: The issue is not observed when creating a new condition.

2024-10-25 07:06 UTC, gedinakova commented
@igdmdimitrov 
1. In the dev demo, clear the root group's return fields
2. Check the canCommit result > it returns false
3. Enter edit mode on the subquery without any other changes
4. Check the canCommit result

Result: It returns true.
Expected result: It should return false because of the root group's state.

2024-10-25 13:03 UTC, gedinakova approved these changes

2024-10-29 10:13 UTC, merged