feat(banner): add collapsed input property to the banner
IgniteUI/igniteui-angular pull request #14935
Opened 2024-10-22 13:38 UTC by georgianastasov

Closes #14890   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-10-24 06:33 UTC, wnvko commented
Setting the `collapsed` input will not fire `opening`, `opened`, `closing` and `closed` events. Also banner changes its state without playing any animation. In this way if you:
- call `banner.open` a nice animation is played, `opening` and `opened` events are fired and banners opens.
- set `collapsed` to false no animation is played, no events are fired and banner gets opened.
Is this behavior desired?

2024-10-24 07:03 UTC, georgianastasov commented
> Setting the `collapsed` input will not fire `opening`, `opened`, `closing` and `closed` events. Also banner changes its state without playing any animation. In this way if you:
> 
> * call `banner.open` a nice animation is played, `opening` and `opened` events are fired and banners opens.
> * set `collapsed` to false no animation is played, no events are fired and banner gets opened.
>   Is this behavior desired?

@wnvko I initially expected this to be the behavior of the `collapsed ` property since it defines the initial state of the banner (expanded or collapsed). I didn’t think that events like `opening` `opened` `closing` or `closed` should fire when the property is setting the initial state. As for the animations, I’m unsure whether they should be included when toggling collapsed, considering its purpose of defining the starting state.

What’s your suggestion on how this should be handled? Should animations and events be tied to the collapsed property as well?

2024-10-24 08:00 UTC, wnvko commented
@georgianastasov 
The new property could be set at any moment. It is not limited to the initial state of the component. You can even change it during the opening/closing animation of the banner. I am not sure how component should behave in these cases. This should be described in the component specification.

2024-10-24 08:11 UTC, georgianastasov commented
@wnvko You're absolutely right, the new `collapsed` property can be set at any point, even during the banner's open/close animations. I believe the key question here is whether the banner events should be triggered from the `collapsed` property or not, and if animation should be incorporated during these state transitions. This should definitely be detailed in the component specification to clarify the intended behavior.

@damyanpetev @simeonoff — Would you mind sharing your thoughts on how we should best implement this? Specifically, whether banner events should be triggered from the `collapsed` property and how to handle animations.

2024-11-19 13:50 UTC, simeonoff commented
Two things I noticed:

1. No events should be fired when setting this property programatically. Also, no animations should be triggered initially. Animations trigger only when the property change programmatically on runtime.
2. To me a boolean property named `expanded` that is set initially to false sounds more logical.

2024-11-19 18:00 UTC, damyanpetev commented
I'll echo parts of what @wnvko and @simeonoff already said:
- I personally agree events shouldn't fire for API calls, though we've had that discussion internally multiple times over the years and never quite settled; it's not entirely consistent across the product even and I don't think we want to open that can of worms for this. But we might not need to, more below.
- The name `collapsed` sort of stuck from toggle directive and propagated to multiple components. Can't say I like it much either, more like used to it. There's also the curios case of two other components - the Nav Drawer and Dialog have **`isOpen`** which I think is a decent alternative. And don't mind that co-existing with a `collapsed` getter.
- Animations honestly a toss depending on the component. For the banner I'm leaning towards without.

Funnily enough, `collapsed` is already an `@Input` on the Expansion Panel that does the same thing and it should be possible for the banner to use it and since _that_ doesn't do animations it sets a pattern. The panel itself has a small issue with this being set while the closing animation runs since it sets the value on end, but that's a bit edge case and can be logged separately.

2025-01-13 12:12 UTC, wnvko requested changes
If you change `expanded` to `true` while close animation is playing nothing happens!

Here is why. If you have banner which is not collapsed, `expanded` is `true` and you set `expanded` to `false` this will call `close` method to the internal `expansionPanel`. This will then call `collapse` method and it will start the close animation. At this point `collapsed` is still `false`. It will change to `true` once animation is finish.
While animation is playing if you change `expanded` to `true` it will call `open` method of the internal expansion panel. This will then call `expand` method. In this method the first check is this:
```ts
        if (!this.collapsed) { // If the panel is already opened, do nothing
            return;
        }
```
As expansion panel's `collapsed` is still `false` nothing will happen here.

2025-01-13 12:12 UTC, wnvko commented on projects/igniteui-angular/src/lib/banner/banner.component.ts
> +    private _isProgrammaticExpanded = false;
can we rename this to something like `shouldFireEvent` or `fireEvent` or anything like this.

2025-01-13 12:12 UTC, wnvko commented on CHANGELOG.md
> +    - Introduced a new `expanded` input property, enabling dynamic control over the banner's state. This property allows the banner to be programmatically set as expanded (visible) or collapsed (hidd
add more information about when animation will be played, which events will be fired and when.

2025-01-16 13:00 UTC, wnvko commented on CHANGELOG.md
> +    - If the `expanded` property changes during an ongoing animation, the current animation will **cancel immediately**, applying the new state without additional animations or events.
This is not how component behaves now.

With current implementation if `expanded` is changed during an animation banner will either do nothing or will start the opposite animation at the point where previous animation has reached.

For example, if the open animation duration is 10 seconds and the close animation duration is 5 seconds, and if `expanded` is set to `true` the open animation will start. Let say animation is at 6 seconds and at this point `expanded` is changed to `false`. Open animation will be stopped, and close animation will start from 3rd second.

If is quite interesting now that `expanded` property and `toggle` method have different behavior.

2025-01-16 13:03 UTC, wnvko commented
One more thing. Please when creating a PR add descriptive names, like `add-expanded-to-banner`. Having this at my side does not help me a lot
![pr-names](https://github.com/user-attachments/assets/2ebab25a-db29-43c9-8f0c-110ba4bcbb88)

2025-01-17 15:59 UTC, wnvko approved these changes

2025-01-23 15:16 UTC, merged