fix(query-builder): delete empty groups - 17.2.x
IgniteUI/igniteui-angular pull request #15035
Opened 2024-11-11 13:28 UTC by igdmdimitrov

Closes #14882  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2024-11-11 13:40 UTC, gedinakova approved these changes

2024-11-12 06:53 UTC, gedinakova requested changes
We should probably add a test here as well.

2024-11-12 07:47 UTC, igdmdimitrov commented
> We should probably add a test here as well.

The test was added in this PR - https://github.com/IgniteUI/igniteui-angular/pull/15014

2024-11-12 08:43 UTC, gedinakova approved these changes

2024-11-12 15:25 UTC, merged