Add validation when disabledDates in date picker is set v.10.0
IgniteUI/igniteui-angular pull request #7996
Opened 2020-08-13 14:56 UTC by PlamenaMiteva

Closes #7800 

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [X] All relevant tags have been applied to this PR
 - [X] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-08-24 10:37 UTC, jackofdiamond5 approved these changes

2020-08-27 13:37 UTC, jackofdiamond5 approved these changes

2020-08-27 16:52 UTC, damyanpetev requested changes

2020-08-27 16:52 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
> +                    this.rawDateString = (res.target as HTMLInputElement).value;
This was not required for the fix, right? :)

2020-08-27 16:52 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
> +        if ((this._ngControl.control.touched || this._ngControl.control.dirty) ||
ehem, the logic change? Should this run if ngModel has no validatos?

2020-08-28 10:41 UTC, damyanpetev approved these changes

2020-08-28 10:56 UTC, merged