Respect closeOnOutsideClick overlay setting
IgniteUI/igniteui-angular pull request #8010
Opened 2020-08-18 14:26 UTC by IvayloG

Closes #7974

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-08-28 13:25 UTC, wnvko requested changes

2020-08-28 13:25 UTC, wnvko commented on projects/igniteui-angular/src/lib/select/select-navigation.directive.ts
> +        } else if (key === 'tab' || event.shiftKey && key === 'tab') {
this is the same as:
```
else if (key === 'tab')
```

2020-08-28 13:25 UTC, wnvko commented on projects/igniteui-angular/src/lib/select/select.component.ts
> +            closeOnOutsideClick: true,
this is the default value, you can skip setting it in the overlay defaults

2020-10-07 07:09 UTC, IvayloG commented
I am closing this PR, as #7974 will be closed as part of the following PR https://github.com/IgniteUI/igniteui-angular/pull/8281

2020-10-07 07:09 UTC, closed without merging