feat(date-picker): Rewiriting the label, #8086
IgniteUI/igniteui-angular pull request #8088
Opened 2020-09-03 14:37 UTC by valadzhov

Closes #8086 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-09-16 10:40 UTC, damyanpetev commented on CHANGELOG.md
> +    - The `labelVisibility` has been removed and now a custom label is set by nesting a <label igxLabel></label> inside the <igx-date-picker><igx-date-picker> tags.
Ummm has it been removed or deprecated?

2020-09-16 10:57 UTC, damyanpetev requested changes

2020-09-16 10:57 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/date-picker/date-picker.component.html
> +        <label igxLabel *ngIf="!labelDirective&&!labelVisibility">Date1</label>
What is this label about? Where did Date1 come from?

2020-09-16 10:57 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
> +     * @deprecated By default the label is set to 'Date'. Use
By default the label is set to 'Date' is not necessary information for this property (the default value is visible). Put something like `Use igxLabel inside the date picker to change the label: <code>`

2020-09-16 10:57 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
> +    @DeprecateProperty(`By default the label is set to 'Date'.`)
Same here - this is a console warning, really doesn't tell me much that the default value is Date :) Consider text similar to my above recommendation - "Use igxLabel.. "

2020-09-16 10:57 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
> +    @DeprecateProperty(`Deprecated. Use
I really don't see how that replaces the visibility functionality. Perhaps this property shouldn't be deprecated yet?

2020-09-16 10:57 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/grids/cell.component.html
> -            [locale]="grid.locale" [(value)]="editValue" [igxFocus]="true" [labelVisibility]="false">
I assume those are hidden for a reason... and can't just be removed like that

2020-09-17 07:47 UTC, valadzhov commented on CHANGELOG.md
> +    - The `labelVisibility` has been removed and now a custom label is set by nesting a <label igxLabel></label> inside the <igx-date-picker><igx-date-picker> tags.
It's been deprecated.

2020-09-18 09:31 UTC, Lipata approved these changes

2020-09-18 10:46 UTC, merged