Make filtering row respect grid's display density
IgniteUI/igniteui-angular pull request #8112
Opened 2020-09-09 09:16 UTC by onlyexeption

Closes #7090 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-09-16 07:03 UTC, StefanIvanov submitted a review, later dismissed

2020-09-17 16:19 UTC, DiyanDimitrov requested changes

2020-09-17 16:19 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html
> +            <igx-input-group #inputGroup type="box" [displayDensity]="displayDensity" (focusout)="onInputGroupFocusout()">
This should probably also be fluent.
```suggestion
            <igx-input-group #inputGroup type="fluent" [displayDensity]="displayDensity" (focusout)="onInputGroupFocusout()">
```

2020-09-18 08:24 UTC, StefanIvanov submitted a review, later dismissed

2020-09-24 12:04 UTC, StefanIvanov approved these changes

2020-09-28 07:28 UTC, igdmdimitrov approved these changes

2020-09-28 09:17 UTC, igdmdimitrov approved these changes

2020-09-28 10:13 UTC, DiyanDimitrov approved these changes

2020-09-28 10:13 UTC, merged