fix(grid): disable focus styles for min parts of the grid
IgniteUI/igniteui-angular pull request #8130
Opened 2020-09-11 10:55 UTC by desig9stein

Closes #7211

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-09-14 06:50 UTC, simeonoff approved these changes

2020-09-14 06:51 UTC, simeonoff requested changes
There are some linting errors.

2020-09-16 10:54 UTC, simeonoff approved these changes

2020-09-17 12:26 UTC, zdrawku approved these changes
Everything looks good, the only thing that I've noticed is a missing child header right border when using the indigo light theme - [I've logged an issue about it](https://github.com/IgniteUI/igniteui-angular/issues/8172)

2020-09-17 12:27 UTC, merged