fix(grid): improve bool cell style templating
IgniteUI/igniteui-angular pull request #8142
Opened 2020-09-14 14:15 UTC by simeonoff

Closes #8100  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-09-15 06:31 UTC, SisIvanova submitted a review, later dismissed

2020-09-15 13:22 UTC, Aleksandyr commented
@simeonoff Please make sure that those two classes are applied on the [tree-cell.component](https://github.com/IgniteUI/igniteui-angular/blob/577f4f887f2be3800df373551c8d0319188f63be/projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html#L21) as well.

2020-09-16 07:06 UTC, Aleksandyr requested changes
Please update the tree-cell.component.html with the respective class either.

2020-09-16 08:25 UTC, Aleksandyr approved these changes

2020-09-16 11:23 UTC, kdinev approved these changes

2020-09-16 12:13 UTC, merged