Rkaraivanov/toolbar refactor
IgniteUI/igniteui-angular pull request #8158
Opened 2020-09-16 10:41 UTC by rkaraivanov

Closes #8055  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-10-06 12:52 UTC, simeonoff requested changes

2020-10-06 12:52 UTC, simeonoff commented on projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.html
>  <div class="igx-grid-toolbar__actions">
Can we perhaps remove this div and move the class to the igx-grid-toolbar actions element?

2020-10-06 12:52 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
>      %igx-grid-toolbar__title {
The title should probably not grow infinitely. It should probably be limited in width.

2020-10-06 12:52 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
> +        box-shadow: 0 5px 5px -3px rgba(0, 0, 0, .26), 0 8px 10px 1px rgba(0, 0, 0, .12), 0 3px 14px 2px rgba(0, 0, 0, .08);
The same goes for this shadow as well.

2020-10-06 12:52 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
> +        border: 0 solid rgba(0, 0, 0, .12);
Shouldn't the color be a gray variant from the palette?

2020-10-07 08:08 UTC, simeonoff requested changes

2020-10-07 08:08 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss
> +/// @requires $elevations
What's the point of passing `$elevations` here if the map is not gonna be used?

2020-10-07 08:08 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
> +    $elevations: $elevations,
Same as my other comment regarding elevations.

2020-10-07 13:20 UTC, simeonoff requested changes

2020-10-07 13:20 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss
> +        elevation: $elevations,
This should be named `elevations` (plural), instead of the singular `elevation`.

2020-10-14 10:15 UTC, simeonoff requested changes

2020-10-14 10:15 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss
> +/// @requires $elevations
This shouldn't be listed as required as it's passed down in the theme itself.

2020-10-14 10:15 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
> +/// @requires $elevations
The same goes for this one.

2020-10-14 10:42 UTC, simeonoff submitted a review, later dismissed

2020-10-27 09:24 UTC, simeonoff submitted a review, later dismissed

2020-10-28 15:21 UTC, ChronosSF requested changes

2020-10-28 15:21 UTC, ChronosSF commented on projects/igniteui-angular/src/lib/test-utils/grid-base-components.spec.ts
> +    <igx-column-actions igxColumnPinning [columns]="grid.columns" *ngIf="showInline"></igx-column-actions>
this is incorrectly merged. We moved away from using a columns input as that results in expressionchangedafterithasbeenchecked exceptions. The columns input is deprecated in favor of the grid input

2020-10-30 11:53 UTC, ddincheva commented
Issues: 

- [ ] When you click over the column hiding/pining button to open the dropdown and click again over the button in order to close it; the dropdown menu is not closed. Also after that if you try to click outside somewhere on the page the dropdown still does not close; If you click over the button once again the error is thrown in the console.

![toolBar](https://user-images.githubusercontent.com/34240583/97701528-3f1a7280-1ab6-11eb-9566-0fcb92ffd912.gif)

- [ ] When there are multiple columns  defined in the grid and you open column pinning/hiding scroll bar is shown on the page rather than on the opened dropdown list;
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/34240583/97701829-b3551600-1ab6-11eb-9c5c-cdf871b36776.png)
Expected: 
![image](https://user-images.githubusercontent.com/34240583/97701837-b6500680-1ab6-11eb-89cd-2af7d7456b3e.png)

2020-10-30 13:35 UTC, Aleksandyr commented
@rkaraivanov I have added several issues I have determined while testing the migrations with the angular samples. They could be found in the word document [here](https://infragisticsinc297-my.sharepoint.com/:w:/g/personal/akamenov_infragistics_com/EWnV3LwgUDNHhW4TbgaLWZABhOEkY2Pri71pULYbm6y2rQ?e=EBNlxw).

2020-11-04 11:05 UTC, ddincheva commented
All the issues described in my previous comment are fixed except that in the 4th checkbox. But a new issue is introduced. When open the "Export" button an error is thrown:
![excellError](https://user-images.githubusercontent.com/34240583/98103801-3a7f0100-1e9e-11eb-90ee-2fbf81588cd7.gif)

2020-11-04 11:56 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component.html
> +    <button #btn igxButton="outlined" name="btnColumnHiding" (click)="toggle(btn, ref, actions)"
@rkaraivanov Can you also add `title` to built-in buttons (at least icon ones) and include those in the localized resources? The native tooltip should be a nice improvement for usability and accessibility I suspect.

2020-11-04 13:45 UTC, rkaraivanov commented on projects/igniteui-angular/migrations/update-11_0_0/index.ts
> +                return (template as Element).attrs.find(attr => attr.name.startsWith('let'))
I was thinking of either emitting a warning message after the migration or to insert a comment above the moved notes, so the user can check them themself.

2020-11-06 12:16 UTC, ChronosSF approved these changes

2020-11-06 12:56 UTC, ChronosSF approved these changes

2020-11-06 13:28 UTC, zdrawku approved these changes

2020-11-06 13:29 UTC, merged