feat(grid-esf): make excel style filtering work like in excel
IgniteUI/igniteui-angular pull request #8193
Opened 2020-09-23 15:10 UTC by onlyexeption

Closes #5813 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-09-30 11:36 UTC, DiyanDimitrov requested changes
Add the feature to the changelog.

2020-09-30 11:36 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> +        this.esf.listData.forEach(i => this.displayedListData.indexOf(i) === -1 ? i.isSelected = false : i.isSelected = true);
We should optimize this.

2020-09-30 11:36 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> +            this.esf.listData.forEach(i => i.isSelected ? i.isFiltered = true : i.isFiltered = false);
```suggestion
            this.esf.listData.forEach(i => i.isFiltered = i.isSelected);
```

2020-10-01 10:46 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> +                if (element.value === this.addToCurrentFilter.value) { return; }
This should work with comparing the objects themselves.
```suggestion
                if (element === this.addToCurrentFilter) { return; }
```

2020-10-01 10:46 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> +            if (!this.displayedListData.slice(indexToStartSlicing, this.displayedListData.length).find(el => el.isSelected === false)) {
The array is still sliced two times. I have meant to have:
```ts
const slicedArray = this.displayedListData.slice(indexToStartSlicing, this.displayedListData.length);
```

2020-10-01 10:59 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> +                this.displayedListData[0].indeterminate = true;
This issue still persists. You could see a console error when typing a search value that doesn't match any items and then delete it.

2020-10-01 11:23 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> +            this.esf.listData.forEach(i => i.isSelected ? i.isFiltered = true : i.isFiltered = false);
The code now is `i.isSelected = i.isFiltered`, shouldn't it be the opposite?

2020-10-01 11:31 UTC, DiyanDimitrov requested changes

2020-10-01 11:31 UTC, DiyanDimitrov commented on CHANGELOG.md
> +        - When filtering, only the rows that match your search term will be visible.
```suggestion
        - When searching items in the Excel Style Filtering menu, only the rows that match your search term will be filtered in.
```

2020-10-01 11:31 UTC, DiyanDimitrov commented on CHANGELOG.md
> +    - **Behavioral Change** - The Excel Style Filtering has been reworked to provide filtering experience such as in Excel. This includes the following changes.
```suggestion
    - **Behavioral Change** - The Excel Style Filtering has been reworked to provide filtering experience such as in Excel. This includes the following changes:
```

2020-10-01 11:31 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> +
Remove empty line.

2020-10-02 12:47 UTC, DiyanDimitrov requested changes

2020-10-02 12:47 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> +    public onInputKeyDown(event): void {
Add `@hidden` and `@internal` to all public members.

2020-10-05 07:51 UTC, DiyanDimitrov approved these changes

2020-10-06 06:52 UTC, igdmdimitrov commented on projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> +                expect(fix.debugElement.query(By.css(FILTER_UI_ROW))).not.toBeNull();
Ctrl+Shift+L should close the Filter Row and the last statement will change

2020-10-06 07:30 UTC, igdmdimitrov commented on projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> +        expect(gridCellValues).toEqual(totalListItems);
If possible - at the end of the test open the filter dialog again and verify the selection state of the 'Select All' button.

2020-10-06 15:33 UTC, DiyanDimitrov approved these changes

2020-10-08 07:46 UTC, DiyanDimitrov approved these changes

2020-10-08 08:14 UTC, DiyanDimitrov approved these changes

2020-10-08 09:06 UTC, merged