feat(tab-nav-drawer): Disable animation. #7157
IgniteUI/igniteui-angular pull request #8255
Opened 2020-10-01 12:48 UTC by valadzhov

Closes #7157 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-10-05 11:14 UTC, kdinev requested changes

2020-10-05 11:14 UTC, kdinev commented on projects/igniteui-angular/src/lib/tabs/tabs.component.ts
> +    public enableAnimation = true;
Should also be `disableAnimation`.

2020-10-05 13:00 UTC, valadzhov commented on projects/igniteui-angular/src/lib/tabs/tabs.component.ts
> +    public enableAnimation = true;
Changed as suggested.

2020-10-05 15:17 UTC, Lipata requested changes
Add also tests for both properties

2020-10-05 15:17 UTC, Lipata commented on CHANGELOG.md
> +    - Added `disableAnimation` input property which enables/disables the animation for transition of the content of the tabs. Set to `false` by default.
```suggestion
    - Added `disableAnimation` property which enables/disables the transition animation of the tabs' content. Set to `false` by default.
```

2020-10-05 15:17 UTC, Lipata commented on projects/igniteui-angular/src/lib/navigation-drawer/README.md
> +| `disableAnimation` | boolean | Enables/disables the animation for the  opening and the closing of the drawer. Set to `false` by default.
```suggestion
| `disableAnimation` | boolean | Enables/disables the animation, when toggling the drawer. Set to `false` by default.
```

2020-10-05 15:17 UTC, Lipata commented on projects/igniteui-angular/src/lib/tabs/README.md
> +| `disableAnimation`| boolean | Enables/disables the animation for transition of the contents of the tabs. Set to `false` by default.
```suggestion
| `disableAnimation`| boolean | Enables/disables the transition animation of the tabs' content. Set to `false` by default.
```

2020-10-05 15:17 UTC, Lipata commented on projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
> +    @HostBinding ('class.igx-nav-drawer--disable-animation')
Add API Code snippet and description

2020-10-05 15:17 UTC, Lipata commented on projects/igniteui-angular/src/lib/tabs/tabs.component.ts
> +    @Input()
Add API Code snippet and description

2020-10-06 08:52 UTC, valadzhov commented on CHANGELOG.md
> +    - Added `disableAnimation` input property which enables/disables the animation for the opening and the closing of the drawer. Set to `false` by default.
Changed as suggested.

2020-10-06 08:52 UTC, valadzhov commented on CHANGELOG.md
> +    - Added `disableAnimation` input property which enables/disables the animation for transition of the content of the tabs. Set to `false` by default.
Changed as suggested.

2020-10-06 08:53 UTC, valadzhov commented on projects/igniteui-angular/src/lib/navigation-drawer/README.md
> +| `disableAnimation` | boolean | Enables/disables the animation for the  opening and the closing of the drawer. Set to `false` by default.
Changed as suggested.

2020-10-06 08:53 UTC, valadzhov commented on projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
> +    @HostBinding ('class.igx-nav-drawer--disable-animation')
Added API code snippet and description.

2020-10-06 08:53 UTC, valadzhov commented on projects/igniteui-angular/src/lib/tabs/README.md
> +| `disableAnimation`| boolean | Enables/disables the animation for transition of the contents of the tabs. Set to `false` by default.
Added API code snippet and description.

2020-10-06 12:14 UTC, desig9stein submitted a review, later dismissed

2020-10-06 12:37 UTC, Lipata submitted a review, later dismissed

2020-10-07 08:57 UTC, Lipata approved these changes

2020-10-07 12:34 UTC, Lipata approved these changes

2020-10-07 13:14 UTC, merged