Vslavov/expansion panel cancel interaction 9.1.x
IgniteUI/igniteui-angular pull request #8269
Opened 2020-10-04 18:54 UTC by ViktorSlavov

Closes #8190   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [x] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [x] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-10-05 11:40 UTC, wnvko requested changes

2020-10-05 11:40 UTC, wnvko commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.common.ts
>      panel: IgxExpansionPanelBase;
please change `panel` to `owner`, as it is coming from `IBaseEventArgs`.
Then you can deprecate `panel`.

2020-10-05 11:40 UTC, wnvko commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts
> +         const eventArgs = { event: evt, panel: this.panel, cancel: false };
add type here
```suggestion
         const eventArgs: IExpansionPanelInteractionEventArgs = { event: evt, panel: this.panel, cancel: false };
```

2020-10-05 11:40 UTC, wnvko commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts
> +            const eventArgs = { event, panel: this.panel, cancel: false };
add type here:
```suggestion
            const eventArgs: IExpansionPanelInteractionEventArgs = { event, panel: this.panel, cancel: false };
```

2020-10-05 11:40 UTC, wnvko commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts
> +            const eventArgs = { event, panel: this.panel, cancel: false };
```suggestion
            const eventArgs: IExpansionPanelInteractionEventArgs = { event, panel: this.panel, cancel: false };
```

2020-10-05 11:40 UTC, wnvko commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts
> +    public onInteraction = new EventEmitter<IExpansionPanelInteractionEventArgs>();
you should update the comment too, as it is pointing to the old event arguments type

2020-10-05 11:40 UTC, wnvko commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.common.ts
> +export interface IExpansionPanelInteractionEventArgs extends IExpansionPanelEventArgs, CancelableEventArgs {}
IMO `ExpansionPanelCancelabelEventArgs` is better naming here.
Additionally we can add `collapsing` and `expanding` event in future, where we can use same type for the event arguments.
Also in most places we are calling cancelable event arguments `Something`**Cancelable**`EventArgs`

2020-10-06 08:09 UTC, ViktorSlavov commented
@wnvko thanks for the review!
Since this is a feature, I'll drop this PR and continue w/ the one [targeting the newest version](https://github.com/IgniteUI/igniteui-angular/pull/8268)

2020-10-06 08:09 UTC, closed without merging