Don't duplicate records in esf menu when filteringIgnoreCase is true.
IgniteUI/igniteui-angular pull request #8286
Opened 2020-10-06 07:50 UTC by onlyexeption

Closes #8162

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-10-07 14:58 UTC, astaev submitted a review, later dismissed

2020-10-08 11:56 UTC, DiyanDimitrov requested changes

2020-10-08 11:56 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
> +
This doesn't seems to be the best place to apply the `filteringIgnoreCase`, it is better to apply it in the `generateUniqueValues` method. Also this solution is not the best in terms of performance. You can see a performance comparison [here](https://stackoverflow.com/a/43046408) and an implementation for case insensitive scenarios [here](https://stackoverflow.com/a/48731445).

2020-10-08 14:34 UTC, DiyanDimitrov requested changes

2020-10-08 14:34 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> +            expect(listItems.length).toBe(3, 'incorrect rendered list items count');
It is good to check the item labels too to be sure the first occurrence is used.

2020-10-08 14:34 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> +            expect(listItems.length).toBe(5, 'incorrect rendered list items count');
Check the item labels too.

2020-10-08 14:34 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
> +                new Map);
Use optional chaining for null values.
```suggestion
            const filteredUniqueValues = columnValues.map(s => s?.toLowerCase()).
                reduce((map, val, i) => map.get(val) ? map : map.set(val, columnValues[i]),
                new Map);
```

2020-10-13 06:23 UTC, DiyanDimitrov approved these changes

2020-10-15 10:54 UTC, merged