feat(input): initial file type implementation
IgniteUI/igniteui-angular pull request #8348
Opened 2020-10-12 14:20 UTC by didimmova

Closes #6544

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-10-27 12:53 UTC, wnvko requested changes
Validation of the input is broken now. As input is hidden it does not get focus, neither it can blur.

2020-10-27 12:53 UTC, wnvko commented on projects/igniteui-angular/src/lib/directives/input/input.directive.ts
> +            if (this.required && fileList?.length > 0) {
this should not happen here. Validation should be done on blur

2020-10-27 13:41 UTC, simeonoff commented on projects/igniteui-angular/src/lib/input-group/input-group.component.html
> +<ng-template #uploadButton>
Should localization be handled in this PR?

2020-10-29 09:17 UTC, simeonoff requested changes

2020-10-29 09:17 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/i18n/input-resources.ts
> +    igx_input_clear_button?: string;
You also need a string for the placeholder.

2021-02-02 08:51 UTC, kdinev commented
@simeonoff Are you going to finish this PR?

2021-02-02 08:58 UTC, simeonoff commented
> @simeonoff Are you going to finish this PR?

@Lipata wanted to take over this PR. We've discussed it several months ago and they wanted to fix some other issues with the input component before incorporating the changes made in this PR. Plus, they didn't really like the implementation introduced here.

2021-02-02 10:14 UTC, kdinev commented
@Lipata Is this inactive/abandoned?

2021-02-03 10:48 UTC, wnvko commented
With current implementation the validation of the file type input does not work. It is not validating the input in template driven form nor it validate it in template driven forms. The main issue here is that the input is hidden and it never gets focused or blurred, and in the end validation fails.

2021-02-04 12:09 UTC, kdinev commented
@wnvko @Lipata Even if validation doesn't work, I would still prefer for the general styling to be merged and the validation to be implemented in the future.

2021-02-05 10:21 UTC, wnvko commented on projects/igniteui-angular/src/lib/directives/input/input.directive.ts
> +            if (this.required && fileList?.length > 0) {
there will be separate PR fixing validation

2021-02-05 10:21 UTC, wnvko submitted a review, later dismissed

2021-02-05 11:55 UTC, wnvko submitted a review, later dismissed

2021-02-05 13:17 UTC, simeonoff submitted a review, later dismissed

2021-02-09 06:58 UTC, wnvko commented
In all themes, when you focus the input, there is no visual indication that the input is active.
In Bootstrap themes when you click on `Upload file` button its border goes out of the input.

2021-02-09 08:16 UTC, simeonoff submitted a review, later dismissed

2021-02-09 09:12 UTC, simeonoff commented
> In all themes, when you focus the input, there is no visual indication that the input is active.
> In Bootstrap themes when you click on `Upload file` button its border goes out of the input.
> There is misalignment between button text and input value in material themes
> ![image](https://user-images.githubusercontent.com/5990334/107327134-4689e880-6ab5-11eb-8375-46900cbe9ead.png)

Fixed the first issue related to focusing the input.
The second issue was related to another issue, which was not related to the file type implementation. It was fixed in master and master has been merged into this branch, so all issues should be resolved now.

2021-02-09 12:34 UTC, wnvko approved these changes

2021-02-09 15:29 UTC, simeonoff approved these changes

2021-02-09 15:29 UTC, merged