fix(dialog): exposed opened property-master #8320
IgniteUI/igniteui-angular pull request #8357
Opened 2020-10-13 12:22 UTC by dobromirts

Closes #8320

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-10-14 08:29 UTC, hanastasov requested changes
Rename the Input to `isOpened` and add a getter (you can use the old getter ;) )

2020-10-14 11:10 UTC, dobromirts commented
> Rename the Input to `isOpened` and add a getter (you can use the old getter ;) )

Done

2020-10-14 11:44 UTC, hanastasov approved these changes

2020-10-14 11:45 UTC, hanastasov requested changes
Fix Tslint errors.

2020-10-15 06:21 UTC, hanastasov approved these changes

2020-10-15 07:05 UTC, hanastasov approved these changes

2020-10-15 07:06 UTC, hanastasov requested changes
When setting the opened property to false, dialog should be closed.

2020-10-15 07:18 UTC, hanastasov submitted a review, later dismissed

2020-10-15 14:22 UTC, HristoP96 requested changes

2020-10-15 14:22 UTC, HristoP96 commented on projects/igniteui-angular/src/lib/dialog/dialog.component.ts
> +     *     let dialogOpen = this.dialog.opened=true;
```suggestion
     *     this.dialog.opened=true;
```

2020-10-15 14:46 UTC, hanastasov approved these changes

2020-10-15 14:47 UTC, HristoP96 approved these changes

2020-10-16 08:50 UTC, damyanpetev commented
Just, FYI on the property name choice - if we are to move away from `on-` prefixed events globally for the product, the current `onOpen` event won't have a clear transformation - will collide with the `open()` method as is. Alternatively, if we properly expose all the events from the underlying toggle directive/overlay service, those are `onOpening` and `onOpened` and the latter will directly collide with this input's name as both will have to be named `opened` after dropping the prefix :)

Also, as the open action can be prevented and the dialog can be closed with interactions (the buttons?) the value bound to the dialog can easily end up out of sync. Unless this is intended to be initial-only property (the feature request seems to be for totally declarative control), the input should come with a matching output `<name>Change` for two-way binding IMO.

Is there a sample with the proposed `*ngIf` usage?

// cc @rkaraivanov

2020-10-16 12:12 UTC, pmoleri commented
@damyanpetev @dobromirts 
About the `opened` naming, I just want to add one data point that you may want to consider, `nav-drawer` uses `isOpen` and is bindable.

2020-10-19 08:01 UTC, rkaraivanov commented
@pmoleri 

Are you interested in the state of the dialog (aka what the navdrawer `isOpen` property does) or do you want to actually show/hide the dialog declaratively?
Can you provide a reference sample?

2020-10-19 20:28 UTC, pmoleri commented
> @pmoleri
> 
> Are you interested in the state of the dialog (aka what the navdrawer `isOpen` property does) or do you want to actually show/hide the dialog declaratively?
> Can you provide a reference sample?

@rkaraivanov in short: show/hide declaratively.
There's an example in the issue [8320 ](https://github.com/IgniteUI/igniteui-angular/issues/8320#issuecomment-707193271)

2020-10-21 12:20 UTC, hanastasov commented
I guess keeping the input name to be `isOpen` will avoid any name collisions in the future, and will be consistent with the nav-drawer naming.

@damyanpetev

2020-10-22 07:52 UTC, damyanpetev commented
@hanastasov @dobromirts Yeah, with `open()` and `opened` for the method/event, don't really have ideas other than `isOpen` for the property :)

For the declarative control, just a reminder from my previous comment that we should consider also adding a `matching output <name>Change for two-way binding`. That way the first example @pmoleri provided will look more like:
```
<igx-dialog
    title="My Dialog"
    [(isOpen)]="this.myDialogShouldBeOpen"
>
    Content
</igx-dialog>
``` 
Still not sure on the ngIf case - likely to mess up the closing animation at the very least.

2020-10-22 13:35 UTC, HristoP96 submitted a review, later dismissed

2020-10-23 06:57 UTC, hanastasov requested changes

2020-10-23 07:40 UTC, hanastasov approved these changes

2020-10-23 07:52 UTC, HristoP96 approved these changes

2020-10-27 07:54 UTC, rkaraivanov approved these changes

2020-10-27 10:14 UTC, kdinev approved these changes

2020-10-27 10:15 UTC, merged

2020-12-16 22:06 UTC, pmoleri commented
> @hanastasov @dobromirts Yeah, with `open()` and `opened` for the method/event, don't really have ideas other than `isOpen` for the property :)
> 
> For the declarative control, just a reminder from my previous comment that we should consider also adding a `matching output <name>Change for two-way binding`. That way the first example @pmoleri provided will look more like:
> 
> ```
> <igx-dialog
>     title="My Dialog"
>     [(isOpen)]="this.myDialogShouldBeOpen"
> >
>     Content
> </igx-dialog>
> ```
> 
> Still not sure on the ngIf in the second case - likely to mess up the closing animation at the very least.

Hi @damyanpetev @dobromirts 
I was trying to use this, under the impression that it would support 2 way binding after what was said in the quoted message, but it doesn't.

This works ok:
```
<button igxButton="raised" igxRipple="white" (click)="this.dialogOpen = true">Show Alert Dialog</button>

<igx-dialog
    [isOpen]="this.dialogOpen"
    (onClose)="this.dialogOpen = false"
    title="Notification"
    message="Your email has been sent successfully!"
    leftButtonLabel="OK"
    (onLeftButtonSelect)="this.dialogOpen = false">
</igx-dialog>
```

This doesn't:
```
<button igxButton="raised" igxRipple="white" (click)="this.dialogOpen = true">Show Alert Dialog</button>

<igx-dialog
    [(isOpen)]="this.dialogOpen"
    title="Notification"
    message="Your email has been sent successfully!"
    leftButtonLabel="OK"
    (onLeftButtonSelect)="this.dialogOpen = false">
</igx-dialog>
```

- Click to open
- Close with the button (works fine, it's still 1 way)
- Click to open
- Esc to close -> the binding is not updated (2 way failed)

Was it supposed to be 2 way?

2020-12-17 12:04 UTC, hanastasov commented
@dobromirts is working on this, it seemed that the component is missing a ControlValueAccessor. I think he is going to push to this    issue.

2020-12-17 12:09 UTC, damyanpetev commented
This is not related or dependent on `ControlValueAccessor` FYI :)

2020-12-17 13:11 UTC, hanastasov commented
@dobromirts will change the implementation to keep the `isOpen` state accordingly. Also, implementation should respect if the open/close events are cancelled.

2020-12-17 13:27 UTC, pmoleri commented
Thanks. BTW, I'm yet to try this kind of binding in real world. But at first glance it looks really promising, I think I no longer need to care about things like `@ViewChild`, checking it `AfterContentInit` or worrying if _Expression has changed after it was checked_.
It seems to me that regular declarative bindings are more robust than the corresponding `dialog.Open()` `.close()` alternatives.

2020-12-18 20:44 UTC, pmoleri commented
Hi, I just noticed another issue. When I initialize with `[isOpen]="true"` the dialog is not measured correctly:
![image](https://user-images.githubusercontent.com/12942794/102659610-745b4c80-4158-11eb-8cbb-41a458854765.png)

This is my workaround in the parent component:
![image](https://user-images.githubusercontent.com/12942794/102659673-91901b00-4158-11eb-9dae-e32eafdb918c.png)