fix(dialog): exposed opened property-10.1.x #8320
IgniteUI/igniteui-angular pull request #8360
Opened 2020-10-13 12:52 UTC by dobromirts

Closes #8320

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-10-15 14:29 UTC, HristoP96 requested changes

2020-10-15 14:29 UTC, HristoP96 commented on projects/igniteui-angular/src/lib/dialog/dialog.component.ts
> +     *     let dialogOpen = this.dialog.opened=true;
```suggestion
     *     this.dialog.opened=true;
```

2020-10-27 10:20 UTC, HristoP96 requested changes

2020-10-27 10:20 UTC, HristoP96 commented on projects/igniteui-angular/src/lib/dialog/dialog.component.ts
> +     * * // get
```suggestion
     *  // get
```

2020-10-27 10:29 UTC, HristoP96 approved these changes

2020-10-27 10:30 UTC, zdrawku approved these changes

2020-10-27 12:03 UTC, merged