Implement resize observer to auto-reset scroll position when scrollbar elements is detached/attached to DOM.
IgniteUI/igniteui-angular pull request #8499
Opened 2020-10-30 16:34 UTC by MayaKirova

Closes #8485   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-11-03 14:45 UTC, ChronosSF commented
Seems to basically crash IE when opening a grid in the dev sample browser.

2020-11-05 12:33 UTC, ChronosSF requested changes

2020-11-05 12:33 UTC, ChronosSF commented on projects/igniteui-angular/src/lib/directives/for-of/base.helper.component.ts
> +        debounceTime(40, undefined))
Let's debounce only on IE11 so that the more used browsers don't get the slight delay in restoring the scroll state

2020-11-05 13:04 UTC, rkaraivanov requested changes

2020-11-05 13:04 UTC, rkaraivanov commented on projects/igniteui-angular/src/lib/directives/for-of/base.helper.component.ts
> +            this._observer.observe(this.nativeElement);
We have a helper function to return an observable from DOM observers.
```typescript
import { resizeObservable } from '../../core/utils';

resizeObservable(this.nativeElement).pipe(destructor)
                .subscribe((event) => this._zone.runTask(() => this.handleMutations(event)));
```
You won't need the `resizeNotify` subject and the manual disconnect of the observer on destroy.

2020-11-06 07:12 UTC, rkaraivanov approved these changes

2020-11-06 08:45 UTC, merged