Ibarakov/fix 7878 master
IgniteUI/igniteui-angular pull request #8511
Opened 2020-11-03 10:37 UTC by onlyexeption

Closes #7878 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-11-03 11:40 UTC, DiyanDimitrov commented on CHANGELOG.md
> +    - **Breaking Change** - Added a new directive for re-templating the header filter icon - `IgxExcelStyleHeaderIconDirective`.
This is not a breaking change.
```suggestion
    - Added a new directive for re-templating the Excel style filtering header icon - `IgxExcelStyleHeaderIconDirective`.
```

2020-11-03 15:37 UTC, DiyanDimitrov requested changes

2020-11-03 15:37 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts
> +    public get iconTemplate() {
Use more specific property name.
```suggestion
    public get esfIconTemplate() {
```

2020-11-03 16:07 UTC, DiyanDimitrov commented
The `igxExcelStyleHeaderIcon` directive does not work for hierarchical grid's row islands.

2020-11-04 12:34 UTC, DiyanDimitrov approved these changes

2020-11-05 09:00 UTC, simeonoff approved these changes

2020-11-05 09:09 UTC, DiyanDimitrov approved these changes

2020-11-05 15:47 UTC, merged