Mpopov/calendar accessibility master
IgniteUI/igniteui-angular pull request #8526
Opened 2020-11-05 09:46 UTC by desig9stein

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-11-06 15:29 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.html
> +            [attr.aria-label]="month | date: 'LLLL'"
It seems `aria-label` must be combined with something that supports one. Like this, on its own applied to a span, at lest NVDA for me reads months as "Clickable Dec" ignoring the nice "December" label :(

2020-11-09 15:09 UTC, zdrawku submitted a review, later dismissed
As we discussed with Damyan, his comment will be addressed with a future release

2020-11-09 15:10 UTC, zdrawku reviewed
@desig9stein could you please update the readme.md file and changelog if necessary

2020-11-09 18:21 UTC, damyanpetev requested changes
Requesting changes mainly for the localization strings comments, the rest might be logged as separate issue.

2020-11-09 18:21 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/calendar/calendar.component.html
> +             {{ monthsViewNumber > 1 ? resourceStrings.first_picker + resourceStrings.of + ' ' + monthsViewNumber + ' ' + resourceStrings.starts_from + ' ' + (getViewDate(obj.index) | date: 'LLLL yyy
Okay, this needs some adjusting - it's rendered for all month views (despite the text being "first of") and it's bound to month that changes for all of views when you navigate to previous/next. I realize Chromevox reads just one of those, but NVDA reads all in succession. For multiple months this only has to be rendered for the first one, right?

Also, there's no space between "first picker" and "of" and unless used elsewhere - you can make that a single locale string like `"First picker of {0} start from"`. There's no reason to translate just "of" out of context, might not even be possible in some languages.

2020-11-09 18:21 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/calendar/calendar.component.html
> +            calendar
Was this supposed to be `resourceStrings.calendar`?

2020-11-09 18:21 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/calendar/calendar.component.html
> +            {{ monthsViewNumber && monthsViewNumber > 1 ?  (resourceStrings.with + ' ' + monthsViewNumber + ' ' + resourceStrings.date_pickers) : ''}}
Same thing as with `of`  just merge those into a single string like ` with {0} date pickers`

2020-11-09 18:21 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/core/i18n/calendar-resources.ts
> + igx_selected_month_is: 'Selected month is',
igx_selected_month? :) New component? It's either component prefixed (hint: they all should be) or not.

2020-11-10 12:52 UTC, damyanpetev approved these changes

2020-11-10 13:00 UTC, zdrawku approved these changes

2020-11-10 13:50 UTC, merged