feat(grid): passing the dom event through editing events Closes #8354
IgniteUI/igniteui-angular pull request #8528
Opened 2020-11-05 14:08 UTC by Aleksandyr

Closes #8354

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-11-09 12:00 UTC, wnvko requested changes
There are several additional places where we can pass the `event` argument.
First allow `IgxGridCRUDService.beginAddRow` to accept `event` argument. Then pass it to `createEditEventArgs` where it is called in the function body.
Other places where we can pass `event`:
- `IgxGridNavigationService.handleAlt` pass the event to `IgxGridCRUDService.beginAddRow`.
- `IgxGridCRUDService.beginRowEdit` pass the event to `createEditEventArgs` call.
- `IgxGridCRUDService.beginAddRow` pass the event to `createEditEventArgs` call.
- `IgxGridCRUDService.enterEditMode` pass the event to `IgxGridCRUDService.beginAddRow` call.
- `IgxGridEditingActionsComponent.startEdit` pass the event to -`IgxGridCRUDService.enterEditMode` call.
- `IgxGridExpandableCellComponent.onIndicatorFocus` pass the event to `GridBaseAPIService.submit_value` call.
- `IgxGridCellComponent.pointerdown` pass the event to `GridBaseAPIService.submit_value call`.

2020-11-09 12:00 UTC, wnvko commented on projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
>          let rowEditArgs = row.createEditEventArgs();
pass `event` here too

2020-11-09 12:00 UTC, wnvko commented on projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
>                  const args = row.createEditEventArgs();
pass `event` here too

2020-11-30 08:02 UTC, wnvko commented
Follow the next steps:
1. In dev samples go to Grid Add Row.
2. Add several rows.
3. Put one of the added rows in edit mode.
4. Hover over other row and click add row button in row overlay.
5. Try to determine why the previous row exited edit mode and submitted its data.

Here is what happens:
- `IgxGridEditingActionsComponent.addRowHandler` is not passing the `event` to `IgxGridBaseDirective.beginAddRowByIndex`.
- `IgxGridBaseDirective.beginAddRowByIndex` in `row.onAnimationEnd` handler the event is not passed to `cell.setEditMode`
- this last one does not even accept the `event` argument, but it should. Once it has the `event` argument it should be passed to `IgxGridCRUDService.enterEditMode`.
- in `IgxGridCRUDService.enterEditMode` call to `beginAddRow` should pass the `event`.
- in `IgxGridCRUDService.beginAddRow` should accept `event` and pass it where event args are generated.

2020-11-30 08:03 UTC, wnvko requested changes
Follow the next steps:
1. In dev samples go to Grid Add Row.
2. Add several rows.
3. Put one of the added rows in edit mode.
4. Hover over other row and click add row button in row overlay.
5. Try to determine why the previous row exited edit mode and submitted its data.

Here is what happens:
- `IgxGridEditingActionsComponent.addRowHandler` is not passing the `event` to `IgxGridBaseDirective.beginAddRowByIndex`.
- `IgxGridBaseDirective.beginAddRowByIndex` in `row.onAnimationEnd` handler the event is not passed to `cell.setEditMode`
- this last one does not even accept the `event` argument, but it should. Once it has the `event` argument it should be passed to `IgxGridCRUDService.enterEditMode`.
- in `IgxGridCRUDService.enterEditMode` call to `beginAddRow` should pass the `event`.
- in `IgxGridCRUDService.beginAddRow` should accept `event` and pass it where event args are generated.

2020-12-04 10:57 UTC, wnvko approved these changes

2020-12-11 16:23 UTC, hanastasov commented
Taking any of the following actions while a cell is in edit mode, will exit edit mode. In the `cellEditExit` event handler and consecutive editing events emitted, the `event` property of the `IGridEditDoneEventArgs` object is undefined:
- resizing a column
- hiding a column through the toolbar or API
- pinning a column through the toolbar or API
- moving a column through the toolbar or API, or drag and drop funct
- paging through the UI or via API
- filtering through in row filtering UI
- ESF filtering actions (filtering, hiding, inning, clear column filter)

2020-12-14 13:10 UTC, ddincheva commented
> Taking any of the following actions while a cell is in edit mode, will exit edit mode. In the `cellEditExit` event handler and consecutive editing events emitted, the `event` property of the `IGridEditDoneEventArgs` object is undefined:
> 
> * resizing a column
> * hiding a column through the toolbar or API
> * pinning a column through the toolbar or API
> * moving a column through the toolbar or API, or drag and drop funct
> * paging through the UI or via API
> * filtering through in row filtering UI
> * ESF filtering actions (filtering, hiding, inning, clear column filter)
> 
> IgxGridEditingActionsComponent should be checked too.

In listed scenarios, the editing is ended due to the fact one of these operations is performed, there is no actual DOM event that is triggered the end editing, that is why the event is undefined. Also when the action is triggered from the grid API, again there is no DOM event that can be passed as an argument.

2020-12-15 12:37 UTC, merged