Mpopov/indigo focus styles
IgniteUI/igniteui-angular pull request #8608
Opened 2020-11-18 09:23 UTC by desig9stein

Closes #8543

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-11-19 12:50 UTC, StefanIvanov commented
The styling is all right I am changing the status to verified

2020-11-20 09:15 UTC, simeonoff requested changes
Ok, but there are some newly added theme properties that remain undocumented.

2020-11-20 09:15 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
> +    $selected-shadow-color: null
You should document this property.

2020-11-20 09:15 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> +    $flat-focus-outline: null,
Missing documentation.

2020-11-20 09:15 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> +    $outlined-focus-outline: null,
Missing documentation.

2020-11-20 09:15 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> +    $raised-focus-outline: null,
Missing documentation.

2020-11-20 09:15 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> +    $fab-focus-outline: null,
Missing documentation.

2020-11-25 13:57 UTC, simeonoff approved these changes

2020-11-26 08:04 UTC, merged