fix(grid-filtering): prevent page hanging when using remote data by disabling animation
IgniteUI/igniteui-angular pull request #8618
Opened 2020-11-19 14:26 UTC by onlyexeption

Closes #8602 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-11-26 16:41 UTC, DiyanDimitrov requested changes

2020-11-26 16:41 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
>              const overlaySettings: OverlaySettings = {
Loading overlaySettings could be moved to a private member like the `rowEditSettings` instead of creating them on each `open` call.

2020-11-26 16:41 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> +                positionStrategy: new ContainerPositionStrategy(),
Remove coma.

2020-11-26 16:41 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
>              }
There is no need to check `collapsed` property. It is checked internally in the toggle methods.

2020-11-27 12:51 UTC, skrustev approved these changes

2020-11-27 13:08 UTC, DiyanDimitrov approved these changes

2020-11-30 08:27 UTC, merged