fix(Monthpicker): rowhead attributes fix
IgniteUI/igniteui-angular pull request #8672
Opened 2020-12-02 15:28 UTC by dobromirts

Closes #https://github.com/IgniteUI/igniteui-angular-samples/issues/2392

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-12-03 08:14 UTC, rkaraivanov requested changes
Uhm, can you just move the attributes back between the element tags? I'm ok if we assume the `data-action` attribute is not needed anymore, but the `role` and `aria-label` should definitely remain.

Also maybe use an actual button element instead of a div marked with `role="button"`

2020-12-08 12:45 UTC, zdrawku approved these changes

2020-12-08 12:55 UTC, zdrawku requested changes
Its strange how this problem passed through the tests, @dobromirts could you please check the test for the month picker and add some if necessary.

2020-12-09 07:27 UTC, rkaraivanov approved these changes

2020-12-09 07:29 UTC, merged