Active node doesn't resets horizontal/vertical scroll positions when page lost focus and regain again - 10.2.x
IgniteUI/igniteui-angular pull request #8725
Opened 2020-12-17 14:19 UTC by ddincheva

Closes #8677   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2020-12-18 12:59 UTC, HristoP96 requested changes
Navigating with tab or shift + tab in the hierarchical grid does not trigger active state on its nested grids:

![HgridNavBut](https://user-images.githubusercontent.com/25771040/102616837-dd36ca80-4140-11eb-9980-cf5d8d5275cb.gif)

2020-12-18 13:00 UTC, HristoP96 reviewed
Sometimes, when naviagting tab or shift + tab this error is thrown:
![image](https://user-images.githubusercontent.com/25771040/102617345-b6c55f00-4141-11eb-998b-8d02d6ce177f.png)

2020-12-18 15:23 UTC, HristoP96 approved these changes

2021-01-04 08:36 UTC, zdrawku approved these changes

2021-01-04 08:36 UTC, merged