feat(excel-exporter): export grouped grid
IgniteUI/igniteui-angular pull request #8742
Opened 2021-01-05 11:18 UTC by onlyexeption

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-01-26 10:39 UTC, gedinakova submitted a review, later dismissed

2021-01-26 10:59 UTC, gedinakova commented
@onlyexeption @DiyanDimitrov Currently, group names for empty values are not consistent for the different value types. More precisely, the group name would be '{Column Name} - null' for string and date columns, and '{Column Name} - ' for number columns. 'null' is not quite user friendly, so I would suggest putting '(Blanks)' for all column types instead (as '(Blanks)' is what Excel generates for empty cell values when filtering for example). What do you thinks?

2021-01-27 10:14 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/excel/excel-files.ts
> +    // Check if implementation can be removed
I think it can be removed.

2021-01-27 10:24 UTC, DiyanDimitrov requested changes

2021-01-27 10:24 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> +    type: number;
Why not `RecordType`?
```suggestion
    type: RecordType;
```

2021-01-27 10:24 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> +export enum RecordType {
```suggestion
export enum ExportRecordType {
```

2021-01-27 10:24 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/excel/excel-exporter-options.ts
> +
This is already defined in the base options class.

2021-01-29 13:03 UTC, DiyanDimitrov reviewed
1. Update changelog.
2. Update ignoreSorting description.

2021-01-29 14:34 UTC, DiyanDimitrov approved these changes

2021-02-01 09:32 UTC, gedinakova approved these changes

2021-02-01 10:21 UTC, DiyanDimitrov approved these changes

2021-02-01 10:23 UTC, merged