Inputs respect column formatter
IgniteUI/igniteui-angular pull request #8764
Opened 2021-01-10 20:57 UTC by mtsvyatkova

Closes #8697 

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [X] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-01-12 11:38 UTC, DiyanDimitrov requested changes

2021-01-12 11:38 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
>              const pipeArgs = this.grid.getColumnByName(expression.fieldName).pipeArgs;
We could cache the column object.
```suggestion
            const column = this.grid.getColumnByName(expression.fieldName);
            const formatter = column.formatter;
            if (formatter) {
                return formatter(expression.searchVal);
            }
            const pipeArgs = column.pipeArgs;
```

2021-01-13 08:46 UTC, DiyanDimitrov approved these changes

2021-01-13 11:12 UTC, hanastasov approved these changes

2021-01-13 13:42 UTC, merged