Preserve focus styles while the component is focused.
IgniteUI/igniteui-angular pull request #8905
Opened 2021-02-04 14:59 UTC by desig9stein

Closes #8507

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-02-08 11:28 UTC, simeonoff requested changes

2021-02-08 11:28 UTC, simeonoff commented on projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
> +        this.nativeCheckbox.nativeElement.focus();
The toggle method already calls the focus on the native checkbox input.

2021-02-08 11:28 UTC, simeonoff commented on projects/igniteui-angular/src/lib/radio/radio.component.ts
> +    public onKeydown(event: KeyboardEvent) {
```suggestion
    public onKeyUp(event: KeyboardEvent) {
```

2021-02-08 11:28 UTC, simeonoff commented on projects/igniteui-angular/src/lib/switch/switch.component.ts
> +    public onKeydown(event: KeyboardEvent) {
```suggestion
    public onKeyUp(event: KeyboardEvent) {
```

2021-02-08 11:28 UTC, simeonoff commented on projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
> +    public onKeydown(event: KeyboardEvent) {
```suggestion
    public onKeyUp(event: KeyboardEvent) {
```

2021-02-12 09:37 UTC, simeonoff submitted a review, later dismissed

2021-02-12 16:12 UTC, kdinev approved these changes

2021-02-12 20:47 UTC, merged