chore(*): Roadmap-m15-update
IgniteUI/igniteui-angular pull request #8908
Opened 2021-02-04 15:27 UTC by radomirchev

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [x] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-02-10 16:31 UTC, kdinev requested changes

2021-02-10 16:31 UTC, kdinev commented on ROADMAP.md
> +1. Date & Time Picker Refactoring
Add igx-tree component to this list.

2021-02-11 11:23 UTC, radomirchev reviewed
added igx-tree component to "to do" list

2021-02-11 11:23 UTC, radomirchev commented on ROADMAP.md
> +1. Date & Time Picker Refactoring
Added

2021-02-11 14:25 UTC, kdinev approved these changes

2021-02-11 14:25 UTC, merged