feat(igxSplitter): Add resizeStart/resizing/resizeEnd events.
IgniteUI/igniteui-angular pull request #8989
Opened 2021-02-15 14:57 UTC by MayaKirova

Closes #8808  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-02-15 15:26 UTC, kdinev requested changes

2021-02-15 15:26 UTC, kdinev commented on projects/igniteui-angular/src/lib/splitter/splitter.component.ts
> +        this.resizing.emit(args);
Shouldn't this be `resizeEnd`?

2021-02-16 07:58 UTC, kdinev approved these changes

2021-02-16 12:05 UTC, ChronosSF approved these changes

2021-02-18 15:03 UTC, merged