refactor(themes): remove unnecessary icon margins
IgniteUI/igniteui-angular pull request #8992
Opened 2021-02-15 15:38 UTC by simeonoff

Closes #8991   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-02-16 07:37 UTC, desig9stein submitted a review, later dismissed

2021-02-16 07:56 UTC, desig9stein commented
I don't think that we need those templates anymore.

``` 
<div class="igx-grid-toolbar__button-space">
      <igx-icon>filter_list</igx-icon>
      <span #ref>
          <ng-content></ng-content>
      </span>
      <span *ngIf="!ref.childNodes.length">
          {{ grid?.resourceStrings.igx_grid_toolbar_advanced_filtering_button_label }
      </span>
</div>
```

I think that you can remove the igx-grid-toolbar__button-space wrapper and the styles that it gives to his child elements.


Here are the places from which it can be removed:

grid-toolbar-advanced-filtering.component.html
grid-toolbar-exporter.component.html
grid-toolbar-hiding.component.html
grid-toolbar-pinning.component.html
grid-column-selection.sample.html

2021-02-18 07:50 UTC, desig9stein requested changes

2021-02-18 07:50 UTC, desig9stein commented on projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
> -        igx-icon + [igxLabel] {
These changes are not connected to the button refactoring, they will break the dropdown items inside the action strip. see the [screenshot](https://imgur.com/3ajKm1D)

2021-02-18 08:23 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
> -        }
This doesn't work when the direction is set to RTL.

2021-02-18 09:28 UTC, merged