Bpenkov/range picker impl pickers base
IgniteUI/igniteui-angular pull request #9011
Opened 2021-02-17 14:53 UTC by jackofdiamond5

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-02-18 12:59 UTC, wnvko requested changes
There are several places with breaking changes in this PR, hope you will add some schematics for this. Also I am not sure why, but there are a lot of `this.whatever` calls in the markup. Should we add this everywhere or remove them all?

2021-02-18 12:59 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-common/calendar-container/calendar-container.component.html
> -        <button #todayButton *ngIf="todayButtonLabel" igxButton="flat" igxRipple (click)="selectToday()">
not related to this PR but `emitCalendarClose` and `selectToday` are not the greatest name we could came up with. Could you change these?

2021-02-18 12:59 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.html
> +        <ng-container *ngTemplateOutlet="dateSeparatorTemplate ? dateSeparatorTemplate : defDateSeparatorTemplate;">
:grinning:

2021-02-18 12:59 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +export class IgxDateRangePickerComponent extends PickersBaseDirective
can we change Picker**s**BaseDirective to `PickerBaseDirective`

2021-02-18 12:59 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +    public mode = InteractionMode.DropDown;
this is a breaking change!

2021-02-18 12:59 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +        this._componentID = this._overlayService
`componentID` is misleading. `overlayId` or something like this?

2021-02-18 12:59 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +        this.selecting.emit(args);
we could emit here the old and new value. This will allow user to validate the selection and to decide whether or not to cancel selection.

2021-02-18 12:59 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +            filter((overlay) => overlay.id === this._componentID),
you have same pipe at four places. Please extract this as done in toggleDirective. Something like this:
```
    private _overlaySubFilter: [MonoTypeOperatorFunction<OverlayEventArgs>, MonoTypeOperatorFunction<OverlayEventArgs>] = [
        filter(x => x.id === this._componentID),
        takeUntil(this.destroy$)
    ];
```
and then
```
...
onWhatever.pipe(...this._overlaySubFilter).subscribe
...
```

2021-02-18 12:59 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +        } else if (range.length <= 0 && this.calendar.monthViews) {
could this be less than 0
:grinning:
```suggestion
        } else if (range.length === 0 && this.calendar.monthViews) {
```

2021-02-26 12:55 UTC, wnvko requested changes

2021-02-26 12:55 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +            case KEYS.ESCAPE:
you can set `closeOnEscape: true` for both dialog and drop down overlay settings, and do not handle `ESC`

2021-02-26 13:00 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +    private overlayId: string;
you have now 6 private members like this`_withUnderScore` and four like this `noUnderScorre`
Please let make this consistent :)

2021-03-01 13:28 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
>          // componentInstance.onTodaySelection.pipe(takeUntil(this._destroy$)).subscribe(() => this.triggerTodaySelection());
not sure why these two lines are commented out, but `cancel` and `today` buttons do nothing now in date picker

2021-03-01 13:28 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +    public mode = InteractionMode.DropDown;
Please update and date range picker dev sample, as now there is no single one in dialog mode

2021-03-01 14:12 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +export class IgxDateRangePickerComponent extends PickersBaseDirective
will be fixed in #8711

2021-03-01 14:14 UTC, wnvko approved these changes

2021-03-01 15:03 UTC, wnvko approved these changes

2021-03-12 18:05 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +                return;
Aren't you supposed to cancel the opening of the overlay as well in this case?

2021-03-12 18:05 UTC, damyanpetev commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
> +        this.subscribeToOverlayEvents();
On second thought, you can prob. used closed as is too

2021-03-12 18:06 UTC, damyanpetev requested changes
failed to select the right review type above...

2021-03-16 12:01 UTC, damyanpetev approved these changes

2021-03-16 12:58 UTC, damyanpetev approved these changes

2021-03-16 13:06 UTC, merged