Grid accessibility
IgniteUI/igniteui-angular pull request #9165
Opened 2021-03-17 08:14 UTC by Aleksandyr

Closes 9028

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-03-19 07:20 UTC, ddincheva requested changes

2021-03-19 07:20 UTC, ddincheva commented on projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
>              <span *ngIf="hasMovableColumns && draggedColumn && pinnedColumns.length <= 0"
@Aleksandyr , aria-activedescendant attribute should be attached to the element that holds the focus/ is marked with tabIndex > = 0/. You can see that if you enable some screen reader if you click on a cell and start navigation with the arrow keys it doesn't manage to read the cell content correctly.

2021-03-19 07:20 UTC, ddincheva commented on projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
>          [summaries]="id | igxGridSummaryDataPipe:summaryService.retriggerRootPipe" [index]="dataView.length"
same applies here

2021-03-19 07:20 UTC, ddincheva commented on projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
>          [style.height.px]='totalHeight' [style.width.px]='calcWidth' #tbody (scroll)='preventContainerScroll($event)'>
same issue as described in the previous comment

2021-03-25 10:22 UTC, ddincheva approved these changes

2021-03-25 15:09 UTC, zdrawku approved these changes

2021-03-25 15:09 UTC, merged