fix(navbar): include ellipsis in navbar title
IgniteUI/igniteui-angular pull request #9183
Opened 2021-03-22 16:05 UTC by SisIvanova

Closes #9175 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-03-23 13:53 UTC, SisIvanova commented
material.io specification - https://material.io/components/app-bars-top#anatomy

2021-03-23 14:02 UTC, DaniMarinov commented
As I have discussed with @SisIvanova, I suggest enlarging the navbar height if the title is too long, according to Material spec.

2021-03-23 16:57 UTC, StefanIvanov commented
I find the approach to alleviate the concerns we have and also note that the [spec](https://material.io/components/app-bars-top#specs) shows two presets when it comes to height Regular at 56px and Extended at 128px

2021-03-24 12:13 UTC, StefanIvanov commented
I don't find any issues and once @simeonoff verifies everything as well we can verify the proposed solution.

2021-03-24 14:09 UTC, simeonoff requested changes

2021-03-24 14:09 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> +@mixin line-clamp($lines, $inline, $vertical) {
This mixin should be a part of the mixins file in the utilities folder.

2021-03-24 14:09 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> +    -webkit-line-clamp: if($lines, $lines, 'initial');
```suggestion
    -webkit-line-clamp: if($lines, $lines, initial);
```

2021-03-24 14:09 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> +    -webkit-box-orient: if($vertical, 'vertical', 'initial');
```suggestion
    -webkit-box-orient: if($vertical, vertical, initial);
```

2021-03-24 14:55 UTC, simeonoff approved these changes

2021-03-25 12:35 UTC, merged