Grids templates refactoring
IgniteUI/igniteui-angular pull request #9256
Opened 2021-04-02 13:28 UTC by rkaraivanov

*feat: Refactored grid header row templates/logic into a separate component to be used by the grids
*feat: Group-by area is encapsulated as its own component
*refactor: Various API changes (internal only). Simplified some templates, abstracted some logic
*refactor: Drag scroll behaviors (column moving, range cell selection) are now aligned with the new grid scroll animation frame
behavior. Got to be smooth..
*refactor: Unit test adjustments

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-06-01 08:25 UTC, simeonoff submitted a review, later dismissed

2021-06-24 12:02 UTC, kdinev requested changes

2021-06-28 11:14 UTC, kdinev approved these changes

2021-06-28 11:23 UTC, simeonoff submitted a review, later dismissed

2021-06-29 10:17 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/grids/group-by-area/group-by-area.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush,
Reordering chips in the group by area doesn't work very well with OnPush strategy. That's why we have removed it in the Tree Grid Group By Area [PR](https://github.com/IgniteUI/igniteui-angular/pull/9625/files?file-filters%5B%5D=.ts#diff-b8e9720ade38180ddb6381d29f61a589f72ee69f7a606e120a44bd459891d10c).

2021-07-06 06:06 UTC, kdinev approved these changes

2021-07-06 07:51 UTC, merged