Utilities cleanup and platform service refactor
IgniteUI/igniteui-angular pull request #9282
Opened 2021-04-07 07:21 UTC by rkaraivanov

* Encapsulated various helper methods for dealing
with browsers and browser inconsistencies into the
`PlatformUtil` service.

* Provide the new service to all components.
* Adjusted unit tests

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-04-07 07:45 UTC, kdinev commented on projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
> +    PlatformUtil,
Remove trailing comma.

2021-04-07 07:47 UTC, kdinev approved these changes

2021-04-07 08:07 UTC, DiyanDimitrov submitted a review, later dismissed

2021-04-07 08:11 UTC, gedinakova commented on projects/igniteui-angular/src/lib/core/utils.ts
> +            // we need that hack - otherwise content won't be measured correctly in IE/Edge
This block is for Firefox, so the comment should probably be different

2021-04-07 08:33 UTC, gedinakova requested changes

2021-04-07 08:33 UTC, gedinakova commented on projects/igniteui-angular/src/lib/core/utils.ts
> +            // we need that hack - otherwise content won't be measured correctly in IE/Edge
This block is for Firefox, so the comment should probably be different

2021-04-07 08:33 UTC, gedinakova commented on projects/igniteui-angular/src/lib/core/utils.ts
> +            // we need that hack - otherwise content won't be measured correctly in IE/Edge
Same as above

2021-04-07 08:59 UTC, gedinakova approved these changes

2021-04-07 11:08 UTC, jackofdiamond5 approved these changes

2021-04-07 11:12 UTC, kdinev approved these changes

2021-04-08 10:36 UTC, kdinev commented
@rkaraivanov Also checking the `bug fix` box, as your changes fix an issue with the input group and server-side rendering.

2021-04-08 14:20 UTC, merged