feat(tabs): Adding tabs class migration #9277
IgniteUI/igniteui-angular pull request #9298
Opened 2021-04-08 14:05 UTC by astaev

Closes #9277

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [X] All relevant tags have been applied to this PR
 - [X] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-04-09 09:21 UTC, gedinakova requested changes

2021-04-09 09:30 UTC, astaev commented on projects/igniteui-angular/migrations/update-12_0_0/index.ts
> +                    // console.log('OFFSET', offset);
Opsss...
Removed

2021-04-09 09:30 UTC, astaev commented on projects/igniteui-angular/migrations/update-12_0_0/index.ts
> +            // Also migrate class from igx-tabs-group to igx-tab-cotnent, if any
Fixed

2021-04-09 15:12 UTC, gedinakova approved these changes

2021-04-12 07:43 UTC, kdinev approved these changes

2021-04-12 08:56 UTC, merged