Migrate grid/row-island/hgrid events as members.
IgniteUI/igniteui-angular pull request #9321
Opened 2021-04-14 08:37 UTC by MayaKirova

Closes #9312  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [x] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-04-14 11:14 UTC, gedinakova requested changes
Based on running the migrations in samples repo, it seems that the following members should be added as well:
- chunkPreload
- chunkLoad
- dataChanged
- dataPreLoad (fails in the template as well)

2021-04-14 11:16 UTC, MayaKirova commented
@gedinakova They will be on separate PR.

2021-04-14 13:59 UTC, gedinakova approved these changes

2021-04-16 14:37 UTC, ChronosSF approved these changes

2021-04-16 14:37 UTC, merged