Ttonev/fix 9318 master
IgniteUI/igniteui-angular pull request #9458
Opened 2021-04-28 11:08 UTC by tishko0

Closes #9318 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-04-28 11:23 UTC, hanastasov submitted a review, later dismissed

2021-05-12 15:03 UTC, hanastasov commented on projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> +        this.cdr.detectChanges();
Is that needed?

2021-05-12 15:06 UTC, hanastasov requested changes
Change the `hasNoData` accessor to what it was befrfe

2021-05-12 15:06 UTC, hanastasov commented on projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> +    public get hasNoData(): boolean {
Since `hasNoData` will not be used in the template, keep its accessor to be private.

2021-05-14 12:54 UTC, kdinev requested changes

2021-05-14 12:54 UTC, kdinev commented on projects/igniteui-angular/src/lib/grids/grid/grid.component.html
> +    <div class="igx-grid__tbody-content" tabindex="0" [attr.role]="dataView.length ? null : 'row'" (keydown)="navigation.handleNavigation($event)" (focus)="navigation.focusTbody($event)"
With Angular 12 you can use the `??` operator!

2021-05-18 12:29 UTC, kdinev approved these changes

2021-05-18 13:57 UTC, merged

2021-05-26 18:03 UTC, GibletJr commented
I appears that this fix (9318) has been released with 10.2.23.  Is it also part of 11.1.11 or will it be part of 11.1.12 or a future release?

2021-05-27 07:01 UTC, kdinev commented
@GibletJr The fix is also included in `11.1.11`.

2021-05-27 23:35 UTC, GibletJr commented
@kdinev - confirmed that the fix is in release in 11.1.11 and resolves the issue for igx-grid; however, found that igx-hierarchical-grid application of the same resolution.

2021-05-28 07:52 UTC, kdinev commented
@tishko0 @MayaKirova @ChronosSF Could you please check why this fix has not applied to the `igx-hierarchical-grid`?

2021-05-28 21:51 UTC, GibletJr commented
@kdinev - thanks for pushing for the change on igx-hierarchical-grid as well.  Is there a separate git issue that I should use to track its completion?

2021-06-03 18:16 UTC, GibletJr commented
@ChronosSF / @kdinev  - still looking for confirmation on pickup and ETA on applying this change to igx-hierarchical-grid?

2021-06-04 06:27 UTC, ChronosSF commented
I reopened the original issue and we'll provide a fix asap.