fix(grid): reduce space between items in column actions
IgniteUI/igniteui-angular pull request #9495
Opened 2021-05-11 06:32 UTC by dobromirts

Closes #9430  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-05-11 08:54 UTC, simeonoff requested changes

2021-05-11 08:54 UTC, simeonoff commented on projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss
> +        min-height: rem(38px);
Ok, use the following values, instead:

```css
padding: rem(4px) rem(16px);
min-height: rem(32px);
```

2021-05-11 10:27 UTC, simeonoff submitted a review, later dismissed

2021-05-12 06:52 UTC, rkaraivanov approved these changes

2021-05-12 06:52 UTC, merged