feat(excel-exporter): add excel limitations
IgniteUI/igniteui-angular pull request #9547
Opened 2021-05-14 10:16 UTC by onlyexeption

Closes #9436 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-05-20 11:15 UTC, gedinakova approved these changes

2021-05-21 08:27 UTC, gedinakova requested changes

2021-05-21 08:27 UTC, gedinakova commented on projects/igniteui-angular/src/lib/services/excel/excel-exporter.ts
> +        if(data.length > EXCEL_MAX_ROWS || firstDataElement?.data.length > EXCEL_MAX_COLS) {
firstDataElement?.data.length is undefined

2021-05-25 07:26 UTC, gedinakova approved these changes

2021-05-25 07:39 UTC, kdinev approved these changes

2021-05-25 07:58 UTC, merged