feat(expansion-panel): add contentExpanding/Collapsing event
IgniteUI/igniteui-angular pull request #9649
Opened 2021-06-03 13:23 UTC by ViktorSlavov

Closes #9648 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [x] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-06-03 13:47 UTC, wnvko requested changes

2021-06-03 13:47 UTC, wnvko commented on projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts
> +     * Emitted when the expansion panel finishes collapsing
this is not true 😛

2021-06-04 07:15 UTC, wnvko submitted a review, later dismissed

2021-06-07 09:10 UTC, Lipata approved these changes

2021-06-07 09:55 UTC, wnvko approved these changes

2021-06-07 13:16 UTC, merged