Support Multi Column Header export
IgniteUI/igniteui-angular pull request #9673
Opened 2021-06-07 14:21 UTC by onlyexeption

Closes #6288 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-06-07 14:24 UTC, onlyexeption commented
Samples were not meant to be committed, but I will return them back to normal once verified, since you can test with them instead of creating a sample component.

2021-06-08 06:14 UTC, gedinakova requested changes

2021-06-08 06:14 UTC, gedinakova commented on projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
> +            expect(grid.pinnedColumns.length).toEqual(5, 'Invalid number of pinned columns!');
Unnecessary verification. This should have been covered in MCH tests with pinning.

2021-06-08 06:14 UTC, gedinakova commented on projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
> +        const isHGrid = true;
Is this left true by mistake?

2021-06-08 06:14 UTC, gedinakova commented on projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> +export enum ColumnType {
Enum's name does not match the values. If we keep 'ColumnType' name, the values should be DataColumn and GroupColumn I guess.

2021-06-08 06:14 UTC, gedinakova commented on projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> +    columnSpans?: number;
It should be singular - columnSpan.

2021-06-11 14:27 UTC, gedinakova requested changes

2021-06-18 14:51 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> +    private getColumns(columns: any[]): IColumnList {
There is no reason to use `any`.
```suggestion
    private getColumns(columns: IgxColumnComponent[]): IColumnList {
```

2021-06-18 14:52 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> +        }
This check should probably be moved inside the `getColumns` method.

2021-06-18 15:01 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
>                  this._ownersMap.get(record.owner).columns;
Probably the same operations should be performed for the `this._ownersMap.get(record.owner).columns` too.

2021-06-18 15:14 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/excel/excel-files.ts
> +    private prepareDataNew(worksheetData: WorksheetData, done: (cols: string, sheetData: string) => void) {
```suggestion
    private prepareDataAsync(worksheetData: WorksheetData, done: (cols: string, sheetData: string) => void) {
```

2021-06-29 10:41 UTC, DiyanDimitrov commented on projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> +    startIndex?: number;
I am ok with `startIndex`. We don't have `endIndex` since it can be calculated from `startIndex + columnSpan`.

2021-06-29 11:43 UTC, DiyanDimitrov submitted a review, later dismissed
We could try to improve this in the future by eliminating the multiple checks for multi-column headers and multiple sorting of the columns array.

2021-06-29 15:50 UTC, gedinakova approved these changes

2021-06-30 09:02 UTC, gedinakova approved these changes

2021-06-30 09:03 UTC, merged