Еmit onSelection event when expected - master
IgniteUI/igniteui-angular pull request #9679
Opened 2021-06-08 10:57 UTC by IvayloG

Closes #9629   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-06-08 13:11 UTC, wnvko commented on projects/igniteui-angular/src/lib/select/select.component.ts
>      public selectItem(newSelection: IgxDropDownItemBaseDirective, event?) {
this method should be called `selectItemAndCloseDropDownIfNeeded` 😢 
We may consider refactor this and call `toggleClose` after call `selectItem`

2021-06-08 13:11 UTC, wnvko approved these changes

2021-06-08 16:36 UTC, ViktorSlavov requested changes
Could you please add a test for the specific use case?
I feel like the event order can be tested w/o much hassle.

2021-06-10 07:12 UTC, ViktorSlavov approved these changes

2021-06-10 07:19 UTC, ViktorSlavov commented
@IvayloG 
Bit of a nit-pick, but since this is a bug fix, could you add a comment for the fix as per our [Coding Guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/General-Naming-and-Coding--Guidelines-for-Ignite-UI-for-Angular#coding-conventions)

2021-06-11 14:20 UTC, merged