fix(drop-down): Preventing default focus on drop down items #8658
IgniteUI/igniteui-angular pull request #9805
Opened 2021-06-29 11:43 UTC by valadzhov

Closes #8658 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-07-06 12:36 UTC, ViktorSlavov requested changes

2021-07-06 12:36 UTC, ViktorSlavov commented on projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
> +import { Component, ViewChild, OnInit, ElementRef, ViewChildren, QueryList, IterableChanges } from '@angular/core';
The imported `IterableChanges` don't seem to be used. If so, please remove them.

2021-07-06 12:36 UTC, ViktorSlavov commented on projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts
> +    handleMousedown(event): void {
The event could be typed as well.
Also, add an accessor modifier, as I think lacking one triggers a lint warning. I know we'll go over all of these eventually, but might as well cross one from the ever-growing list
```suggestion
    public handleMousedown(event: MouseEvent): void {
```

2021-07-07 12:47 UTC, Lipata approved these changes

2021-07-07 13:13 UTC, ViktorSlavov approved these changes

2021-07-08 10:34 UTC, merged