Update disabled with CD strategy OnPush
IgniteUI/igniteui-angular pull request #9837
Opened 2021-07-08 15:10 UTC by jackofdiamond5

Closes https://github.com/IgniteUI/igniteui-angular/issues/9776

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-07-12 06:35 UTC, wnvko requested changes

2021-07-12 06:35 UTC, wnvko commented on projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
> +            it('should properly set/update disabled when ChangeDetectionStrategy.OnPush is used', fakeAsync(() => {
actually this testing if `interval` is working and correctly sets the component input. This does not test if picker's inputs are disabled. IMO you should test:
1. If when disabled is set to `true` inputs are disabled.
2. When change disabled run-time inputs change accordingly.

Both above in component with change detection strategy set to OnPush.

2021-07-13 13:23 UTC, wnvko approved these changes

2021-07-13 13:39 UTC, Lipata approved these changes

2021-07-14 12:07 UTC, merged