Support column header freezing on export
IgniteUI/igniteui-angular pull request #9930
Opened 2021-07-28 11:42 UTC by MonikaKirkova

Closes #9863 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-08-09 13:18 UTC, gedinakova requested changes
Add logic for freezing the top header line when exporting hierarchical grid.

2021-08-13 07:01 UTC, gedinakova requested changes

2021-08-13 07:02 UTC, gedinakova requested changes
Please, add this feature to the CHANGELOG.

2021-08-16 06:59 UTC, gedinakova commented
@MonikaKirkova Please, retarget this PR to master.

2021-08-19 07:08 UTC, gedinakova approved these changes

2021-08-19 12:40 UTC, onlyexeption approved these changes

2021-08-19 12:43 UTC, merged