fix(time-picker): fix time picker pan event #9717
IgniteUI/igniteui-angular pull request #9973
Opened 2021-08-06 07:07 UTC by PlamenaMiteva

Closes #9717 

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [X] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

2021-08-12 13:25 UTC, ViktorSlavov requested changes
Is it possible to add a test for the scenario?

2021-08-17 07:01 UTC, ViktorSlavov approved these changes

2021-08-17 09:07 UTC, jackofdiamond5 commented on projects/igniteui-angular/src/lib/time-picker/time-picker.directives.ts
> +        this.touchManager.addEventListener(this.elementRef.nativeElement, 'pan', this.onPanMove, hammerOptions);
I think it's a good idea to destroy the `touchManager`  in `ngOnDestroy` since it may cause memory leaks.

2021-08-20 06:34 UTC, ViktorSlavov approved these changes

2021-08-20 06:37 UTC, jackofdiamond5 approved these changes

2021-08-20 06:40 UTC, Lipata commented
Having threshold 10 for hammer.js config seems fine for both Android and iOS devices. However, because there isn't a scroll animation and inertia the experience seems that can be improved a lot. There is a separate issue for that: #6292.

2021-08-20 06:40 UTC, merged